### ISSUE TITLE
[BUG] check-kmod-load-unload fails on MTL

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#1037]
TPLG=/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg MODEL=MTLP_RVP_HDA ~/sof-test/test-case/check-kmod-load-unload.sh 
Polling 'sof_firmware_boot_complete --since=@1684343454' every 1s for 10s
Command 'sof_firmware_boot_complete --since=@1684343454' timed out after 10s and 11 attempts
2023-05-17 17:11:08 UTC [INFO] Test Result: FAIL!

However running the kmod scripts works fine.

It's likely a timeout value that's not long enough for MTL. Can we increase it to 70s as done for the boot?

@fredoh9 @marc-hb @keqiaozhang this is a gap in our coverage, we do need to start testing module load/unload - possibly with a reduced number of cycles since we lose one minute with the i915 issue

cc:
- #1033

**Comment by marc-hb** [comment]
This is not a sof-test bug, this is new, platform-specific timeout feature (not questioning the priority)

This i915 timeout/bug has been a royal pain all across the board, is there really no way to avoid it?

**Comment by plbossart** [comment]
we already have a 70s timeout in other parts of sof-test, so I will assert that it's a bug. This should just work with the delay being handled.

We have the same issue for all FPGA tests btw, the tests need to deal with the i915 60s wait.

**Comment by marc-hb** [comment]
Re-opening because this is not in any test plan yet.

**Comment by keqiaozhang** [comment]
There's an open issue for MTL when testing kmod. https://github.com/thesofproject/linux/issues/4442

**Comment by marc-hb** [comment]
I checked the last daily (32811) and the test is now passing on MTL, probably has for a while. However it's still not enabled on PR testing: https://sof-ci.01.org/softestpr/PR1110/build783/devicetest/index.html (#1110).

**Comment by plbossart** [comment]
probably because of the 60s graphics timeout, but this one will be removed "soon"

**Comment by marc-hb** [comment]
Pretty sure we did the work for this test to pass even with the i915 60s timeout.

Moreover the timeout happens only once right after boot AFAIK.

For sure daily tests haven't been affected one way or the other.

So I think we just add it back.

**Comment by keqiaozhang** [comment]
We have been enabling the kmod related tests in our mtl-daily test for weeks now. I just enabled them in PR testing.

**Comment by marc-hb** [comment]
It's passing now, thanks @keqiaozhang and everyone else!
