### ISSUE TITLE
[BUG] suspend-resume test fails with errors [drm] *ERROR* GT0 in ADLP_SKU0B00_SDCA

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#1048]
**Describe the bug**

There are simliar errors in booting time
```
[   23.586975] kernel: i915 0000:00:02.0: vgaarb: deactivate vga console
[   23.587284] kernel: i915 0000:00:02.0: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
[   23.588850] kernel: i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[   23.603890] kernel: i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.19)
[   23.689588] kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.5.1
[   23.689628] kernel: i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[   23.698890] kernel: i915 0000:00:02.0: [drm] GT0: HuC: authenticated!
[   23.699713] kernel: i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[   23.699743] kernel: i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[   23.700740] kernel: i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[   23.701132] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.701253] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT

```

suspend-resume fails with these errors, "[drm] *ERROR* GT0:"
```
[ 6646.170236] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GuC initialization failed -ENXIO
[ 6646.170237] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Enabling uc failed (-5)
[ 6646.170238] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize GPU, declaring it wedged!
```

**To Reproduce**
[Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug)](cmd: TPLG=/lib/firmware/intel/avs-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg MODEL=ADLP_SKU0B00_SDCA_IPC4ZPH ~/sof-test/test-case/check-suspend-resume.sh -l 50)

**Detail Info**

- Kernel Branch: topic/sof-dev
- Kernel Commit: [a84a4539c244](https://github.com/thesofproject/linux/commit/a84a4539c244)
- SOF Branch: main
- SOF Commit: [b9b030757f47](https://github.com/thesofproject/sof/commit/b9b030757f47)
- Zephyr Commit: [zephyr-v3.3.0-4292-g7d54586751cf](https://github.com/zephyrproject-rtos/zephyr/commit/zephyr-v3.3.0-4292-g7d54586751cf)

Intel internal daily test: planresultdetail/26938

cc:
- #786

**Comment by marc-hb** [comment]
Is this reproducible?

**Comment by marc-hb** [comment]
We had GuC errors before:
- #786

**Comment by fredoh9** [comment]
same error was reproduced today.
Intel internal daily test: planresultdetail/28251?model=ADLP_SKU0B00_SDCA_IPC4ZPH&testcase=check-suspend-resume-50

**Comment by fredoh9** [comment]
The failure is not only with suspend-resume test but also with booting log

one failure on verify-kernel-boot-log,
planresultdetail/33979?model=ADLP_SKU0B00_SDCA-ipc4&testcase=verify-kernel-boot-log

**Comment by marc-hb** [comment]
Did you mean:
- #1104

**Comment by fredoh9** [comment]
Missed these error from the boot.
```
===========================>>
[    7.838741] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[    7.838762] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
<<===========================
```

planresultdetail/35929?model=ADLP_SKU0B00_SDCA-ipc4&testcase=verify-kernel-boot-log

**Comment by fredoh9** [comment]
https://github.com/thesofproject/sof-test/pull/1104 fixed suspend-resume failure.
New issue is created for booting errors.
