### ISSUE TITLE
[new feature] pipeline filtering enhancement

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#105]
- Currently, we globally block DMIC16k (WOV pipeline) to prevent test failure on this pipeline, but this solution will stop us from writing WOV automation test cases in the future.
- We may need to export pipeline with some specific component, such as "all pipeline with EQ", "playback with PGA", "capture with SRC".
So we need to enhance current pipeline filtering feature.

My thought is:
- retain global ignore list, and add a local ignore list. (cases not use DMIC16k ignore it locally)
- add a with list, this help us to get pipeline in "type" with "component"
The final string passed to `func_export_pipeline` should be:
> "type list; with list; ignore list"    For example:
>"type:playback,capture;with:EQ,PGA;ignore:DMIC16k" OR
>"playback,capture;EQ,PGA;DMIC16k"

We also need to make some change to func_export_pipeline and sof-tplgreader.py.

if spilit with bash is tedious, we can provide new python sof-util.py, and use Python to do this. in fact, the sof-combinatoric.py from Wubin, can also be regarded as a util, and can be merged into sof-util.py.

The above solution can also help to get all pipeline without EQ: "type:playback,capture;;ignore:EQ"

**Comment by aiChaoSONG** [comment]
@xiulipan @Bin-QA @fredoh9 @stripes416 @libinyang @keqiaozhang please leave your comments if you have.

**Comment by Bin-QA** [comment]
`TPLG_IGNORE_LST` you can reset it for your test-case

the common array, you also can redefine it
`unset` to cleanup bash variable

So I don't think you need to write a new function 
on the other hand, you means ignore seems: 
 ignore 'pcm:' so this feature already at sof-tplgreader.py  
you can give complex parameter to get it

**Comment by aiChaoSONG** [comment]
> `TPLG_IGNORE_LST` you can reset it for your test-case
> 
> the common array, you also can redefine it
> `unset` to cleanup bash variable
> 
> So I don't think you need to write a new function
> on the other hand, you means ignore seems:
> ignore 'pcm:' so this feature already at sof-tplgreader.py
> you can give complex parameter to get it

@Bin-QA  we can overwrite TPLG_IGNORE_LST, so the ignore part can removed how about the "with part"? is there any way to get all pipeline with EQ?

**Comment by Bin-QA** [comment]
@aiChaoSONG 
```
./sof-tplgreader.py -h

  -f FILTER [FILTER ...], --filter FILTER [FILTER ...]
                        setup filter, this value is format value,
                        string format is 'key':'value','value'
                        for example: Get "type" is "capture"
                        type: capture
                        for example: Get "type" is "capture, both" and "fmt" is S16_LE
                        type:capture,both fmt:S16_LE
  -b IGNORE [IGNORE ...], --ignore IGNORE [IGNORE ...]
                        setup ignore list, this value is format value,
                        string format is 'key':'value','value'
                        for example: ignore "pcm" is "HDA Digital"
                        pcm:HDA Digital
```

here you can find `filter` design for catch 
which pipeline with which filed keyword and content  
the code logic is same with `ignore`  
so here I think we need to modify the sof-tplgreader to dump the EQ right?  
current without output format, it is hard to say how to modify  

some interesting usage for sof-tplgreader: 
1. simultaneous-playback-capture.sh to remove both,  
`for i in $(sof-tplgreader.py $tmp_tplg -d id -v)`  
here just dump the pipeline id, so I can use the duplicate id to know this pipeline whether is both  
2. verify-pcm-list.sh to remove both
`$(sof-tplgreader.py $tplg_file -d id pcm type -o)`  
here dump `id pcm type` with sort,  
so it will same with /proc/asound/pcm content with order  

So here we need to dump the EQ is 1st, then discuss how to use it  
maybe add new filed, content is EQ, so we can direct to filter to got it

**Comment by aiChaoSONG** [comment]
https://github.com/thesofproject/sof-test/pull/129 is merged, task is done
