### ISSUE TITLE
[BUG] ignore ata2 COMRESET failed errors

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#1106]
https://sof-ci.01.org/linuxpr/PR4597/build6688/devicetest/index.html?model=JSL_RVP_NOCODEC&testcase=verify-kernel-boot-log

===========================>>
[   10.842496] kernel: ata2: COMRESET failed (errno=-16)
[   20.874488] kernel: ata2: COMRESET failed (errno=-16)
[   55.918493] kernel: ata2: COMRESET failed (errno=-16)
<<===========================

**Comment by marc-hb** [comment]
I disabled that device. We don't want to run tests with flaky hard drives, that already cost us months of work in the past, see #948 and links there.
