### ISSUE TITLE
[BUG] check-performance.sh failed with ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#1108]
**Describe the bug**

check-performance.sh failed with ValueError: invalid literal for int()

```
2023-10-02 14:41:20 UTC [REMOTE_INFO] Checking SOF component performance
2023-10-02 14:41:20 UTC [REMOTE_COMMAND] sof_perf_analyzer.py --skip-to-first-trace --kmsg=/home/ubuntu/sof-test/logs/check-performance/2023-10-02-14:40:46-4847/dmesg.txt --out2csv /home/ubuntu/sof-test/logs/check-performance/2023-10-02-14:40:46-4847/sof_perf.txt /home/ubuntu/sof-test/logs/check-performance/2023-10-02-14:40:46-4847/mtrace.txt
Traceback (most recent call last):
  File "/home/ubuntu/sof-test/tools/sof_perf_analyzer.py", line 323, in 
    main()
  File "/home/ubuntu/sof-test/tools/sof_perf_analyzer.py", line 316, in main
    process_kmsg_file()
  File "/home/ubuntu/sof-test/tools/sof_perf_analyzer.py", line 222, in process_kmsg_file
    widget_id = int('0x' + widget_id[-6:], 16)
ValueError: invalid literal for int() with base 16: '0x cmd 1'
2023-10-02 14:41:20 UTC [REMOTE_ERROR] SOF component performace analysis tool exit with error
2023-10-02 14:41:20 UTC [REMOTE_INFO] Test Result: FAIL!
```

Most recent failure link is
planresultdetail/32602?model=MTLP_SDW_AIOC-ace1_0-ipc4&testcase=check-performance

**To Reproduce**
Test with MTLP_SDW_AIOC
TPLG=/lib/firmware/intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l23-rt714-l1.tplg MODEL=MTLP_SDW_AIOC-ace1_0-ipc4 SOF_TEST_INTERVAL=5 ~/sof-test/test-case/check-performance.sh

**Comment by marc-hb** [comment]
From: @aiChaoSONG 
Date: Monday, 25 September 2023 at 19:03
Subject: RE: Daily report summary -WW39.1

The module name parsing from the kernel message is based on pattern like this:
```
[  298.066895] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: Create widget mixout.21.1 instance 0 - pipe 21 - core 0
[  298.066907] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x40000003|0x1000a: MOD_INIT_INSTANCE [data size: 40]
```

A message that containing `Creating widget`, and a following message that shows the MOD_INIT_INSTANCE IPC message content. In mtrace log, we only have module id(0x3, 4 hex bits lsb) and instance id(0x0, two hex bits msb), that is 0x000003, by matching 0x40000003, we get the component name mixout.2.1.
 
The assumption is true in most cases, but sometimes may be wrong. I could try to fix it.

**Comment by marc-hb** [comment]
> The assumption is true in most cases, but sometimes may be wrong

When exactly can it be wrong? Is it because of a (non-performance) bug? If yes then the test should still fail; just with a better error message.

**Comment by btian1** [comment]
@fredoh9 , could you attach an dmesg.txt file for further debug this isssue? Chao shared some ideas to me, I can continue work on this issue.

**Comment by fredoh9** [comment]
@btian1 here you are,
[dmesg-performance.txt](https://github.com/thesofproject/sof-test/files/13207962/dmesg-performance.txt)
This is downloaded from one of latest daily test result.

link: planresultdetail/33757?model=MTLP_SDW_AIOC-ace1_0-ipc4&testcase=check-performance

**Comment by btian1** [comment]
@fredoh9 did you observe this issue on other platform? I can reproduce this with MTLP_SDW_AIOC, not sure other platforms, @plbossart may want to have a check from kernel side, and see whether can have a fix from kernel side.

**Comment by marc-hb** [comment]
> I can reproduce this with MTLP_SDW_AIOC, not sure other platforms

If you can easily reproduce this logging issue in at least one configuration then that is great news. Focus the debug and analysis on that configuration for now. Don't submit any fix before understanding and explaining the problem.

**Comment by fredoh9** [comment]
I saw the error only with MTLP_SDW_AIOC

**Comment by fredoh9** [comment]
I was wrong, found in MTLP_RVP_HDA also

[dmesg-mtl-hda.txt](https://github.com/thesofproject/sof-test/files/13367948/dmesg-mtl-hda.txt)

Intel internal link:
planresultdetail/34694?model=MTLP_RVP_HDA&testcase=check-performance

**Comment by fredoh9** [comment]
For HDA, only two failure was reported for a month. Except today failure, last failure was 2023-10-17 17:27:57.

**Comment by marc-hb** [comment]
Fixed by
- https://github.com/thesofproject/sof-test/pull/1122

**Comment by btian1** [comment]
Thanks, Marc, and with one more PR to kernel:
https://github.com/thesofproject/linux/pull/4709
https://github.com/thesofproject/sof-test/pull/1122
