### ISSUE TITLE
[sof-docs] update sof-test part

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#112]
Have a section about sof-test:

- cases
- return values
- tools
- how to develop and take part in

**Comment by Bin-QA** [comment]
- [x]  return values at [README](https://github.com/thesofproject/sof-test/blob/master/README.md#test-case-result)

**Comment by xiulipan** [comment]
@marc-hb @keqiaozhang @aiChaoSONG can we close this issue, I think the README is pretty good now

**Comment by marc-hb** [comment]
Agreed. Any issue left with the README can now be directly submitted as PRs, no need for a github issue.
