### ISSUE TITLE
[BUG] DRM error to filter?

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#1147]
https://sof-ci.01.org/linuxpr/PR4759/build875/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-suspend-resume-with-capture-5

````
2024-01-04 03:50:44 UTC [ERROR] Caught kernel log error
===========================>>
[ 4877.409903] kernel: i915 0000:00:02.0: [drm] *ERROR* Unclaimed access detected prior to suspending
````

**Comment by marc-hb** [comment]
This happened only once and only after ~20 iterations. Let's wait and see if it becomes more frequent.

**Comment by marc-hb** [comment]
Please re-open if more frequent then once per week or two.

We have (at least) suspend/resume failures on pretty every test run so our bar is not very high...
