### ISSUE TITLE
[BUG] Kernel Boot Log test failing due gdm-x-session closed and script exits

### ISSUE THREAD

**Issue by ssavati** [thesofproject/sof-test#1165]
**Description**
Test script exited abruptly. A new log flooded related gdm-x-session which we not see in passing test

**To Reproduce**
ssh to any LNL device like jf-lnlm-rvp-nocodec-1 and run test
TPLG=/lib/firmware/intel/development/sof-lnl-nocodec.tplg MODEL=LNLM_RVP_NOCODEC SOF_TEST_INTERVAL=5 ~/sof-test/test-case/verify-kernel-boot-log.sh
detail log
[log1.txt](https://github.com/thesofproject/sof-test/files/14853583/log1.txt)

**Expected behavior**
Test should pass without errors

**Detail Info**
https://sof-ci.ostc.intel.com/#/result/planresultdetail/39354

2) Test report ID (if you find it from test report)
    * ID: 39354
3) Test DUT Model (or a brief discribtion about the device)
    * LNLM_RVP_NOCODEC
    * LNLM_RVP_HDA
    * LNLM_SDW_AIOC

4) Test case (what test script and how you run it)
    * TPLG=/lib/firmware/intel/development/sof-lnl-nocodec.tplg MODEL=LNLM_RVP_NOCODEC SOF_TEST_INTERVAL=5 ~/sof-test/test-case/verify-kernel-boot-log.sh

**Screenshots or console output**
SOF CI Report : 39354 model LNLM_RVP_NOCODEC testcase=verify-kernel-boot-log
SOF CI Report : 39354 model=LNLM_RVP_HDA  testcase=verify-kernel-boot-log
SOF CI Report : 39354 model=LNLM_SDW_AIOC testcase=verify-kernel-boot-log

**Comment by marc-hb** [comment]
@ssavati you must plug either a monitor or HDMI dummy plug faking a monitor. It's complicated, see long story in https://github.com/thesofproject/sof-test/discussions/998

For some context about HDMI plugs see recent (and different) issue #4861

**Comment by ssavati** [comment]
@marc-hb Today i have looked into It. Unfortuanetly LNL RVP does not have any HDMI port. 

Few more observation
- on all LNL RVP with 6.9.0* kernel ubuntu UI is not coming up but with 6.2.0-33-generic suuccesfuly boot to UI
- with 6.9.0* kernel boot stuct at below screenshot but we able to ssh. Do you have any further suggestion to try me

![image](https://github.com/thesofproject/sof-test/assets/41477060/33c35ddf-014a-4013-a2c1-91bd9360f9fb)

**Comment by marc-hb** [comment]
> Unfortuanetly LNL RVP does not have any HDMI port.

One display is enough. Does not have to be HDMI. Do we have RVPs without any eDP panel? @fredoh9 says no.

> on all LNL RVP with 6.9.0* kernel ubuntu UI is not coming up but with 6.2.0-33-generic suuccesfuly boot to UI

This is bad, I will try to reproduce.

**Comment by marc-hb** [comment]
@ssavati LNL graphics are very much a work in progress.

the workaround is to disable the GUI for now:

```
sudo systemctl mask --now gdm3
```

This also helps with this test:
```
sudo systemctl mask --now fwupd-refresh.service
```

**Comment by ssavati** [comment]
Thanks @marc-hb . Look Someone applied above workaorund to BA Devices. I checked manually GUI disabled on all BA LNL devices and Test are paasing when i execute manullay. Let wait for today;s Daily results passes or not.

**Comment by ssavati** [comment]
@marc-hb Test are passing in daily_lnl/39494" on 08 Apr 20024 so closing this issue. Once LNL graphics is stable. we will recheck GUI enabled.

**Comment by marc-hb** [comment]
Thanks @ssavati , feel free to re-open if needed!
