### ISSUE TITLE
/sys/debug/   fw_profile/ipc_type: permission denied

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/sof-test#1171]
#1167 does not work: it's at least missing a few `sudo`. I think you didn't notice because you run sof-test as root but that's not how it's usually tested.

https://sof-ci.01.org/softestpr/PR1167/build265/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=verify-kernel-module-load-probe

```
2024-04-05 14:58:59 UTC [REMOTE_INFO] Starting func_exit_handler(0)
cat: /sys/kernel/debug/sof/fw_profile/ipc_type: Permission denied
2024-04-05 14:58:59 UTC [REMOTE_WARNING] using pre kernel 6.9 backwards-compatible fallback with ipc_type kernel parameter
cat: /sys/kernel/debug/sof/fw_profile/ipc_type: Permission denied
2024-04-05 14:58:59 UTC [REMOTE_WARNING] using pre kernel 6.9 backwards-compatible fallback with ipc_type kernel parameter
2024-04-05 14:58:59 UTC [REMOTE_INFO] pkill -TERM -f mtrace-reader.py
2024-04-05 14:58:59 UTC [REMOTE_INFO] ktime=123 sof-test PID=3129: ending
2024-04-05 14:58:59 UTC [REMOTE_INFO] Test Result: PASS!
```

_Originally posted by @marc-hb in https://github.com/thesofproject/sof-test/issues/1167#issuecomment-2046038705_
            

cc:
- #1166

**Comment by marc-hb** [comment]
> I think you didn't notice because you run sof-test as root but that's not how it's usually tested.

You can borrow any CI device to test and fix, no need to change the configuration of yours.

**Comment by plbossart** [comment]
I am a bit confused here. The two files have the same permissions and use the same cat command.

````
root@jf-cml-hel-rt5682-05:~# ls -l /sys/kernel/debug/sof/fw_profile/ipc_type
-r--r--r-- 1 root root 0 Apr  9 16:35 /sys/kernel/debug/sof/fw_profile/ipc_type
root@jf-cml-hel-rt5682-05:~# ls -l /sys/module/snd_sof_pci/parameters/ipc_type 
-r--r--r-- 1 root root 4096 Apr  9 21:22 /sys/module/snd_sof_pci/parameters/ipc_type
````
What causes one to complain and not the other?

**Comment by marc-hb** [comment]
/sys/kernel/debug is a different filesystem / mount point.
```
ls -ld /sys/kernel/debug
drwx------ 38 root root 0 Apr  8 18:06 /sys/kernel/debug
```

**Comment by marc-hb** [comment]
This seems fixed, please re-open if seen again.
