### ISSUE TITLE
[BUG] MTLP_RVP_NOCODEC failed suspend/resume Test with Asix driver error

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#1175]
CMD:  TPLG=/lib/firmware/intel/development/sof-nocodec-bt-mtl-lbm.tplg MODEL=MTLP_RVP_NOCODEC-bluetooth-offload SOF_TEST_INTERVAL=5 ~/sof-test/test-case/check-suspend-resume.sh -l 50

Failed with asix driver error
===========================>>
[ 6512.729010] kernel: ax88179_178a 4-2:1.0 eth0: NETDEV WATCHDOG: CPU: 18: transmit queue 0 timed out 5134 ms
<<===========================

Intel internal test link:
planresultdetail/39820?model=MTLP_RVP_NOCODEC-bluetooth-offload&testcase=check-suspend-resume-50
DUT: jf-mtlp-rvp-nocodec-8

**Comment by marc-hb** [comment]
If this happens once a month then let's do nothing.

If this happens too often then please try another network adapter? We really don't want to use unreliable ones.

Unreliable networking is incredibly time-consuming to debug so let's try not to ignore these errors as much as possible, we're already ignoring too many of them.

**Comment by marc-hb** [comment]
Please re-open if this becomes frequent.
