### ISSUE TITLE
[BUG] New v6.10 errors to filter out

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#1198]
New set of useless errors with 6.10-rcX (https://github.com/thesofproject/linux/pull/5009)

https://sof-ci.01.org/linuxpr/PR5009/build3055/devicetest/index.html?model=CML_HEL_RT5682-ipc3&testcase=verify-kernel-boot-log
[    0.520780] kernel: acpi-fan INT3404:00: probe with driver acpi-fan failed with error -22

https://sof-ci.01.org/linuxpr/PR5009/build3052/devicetest/index.html?model=LNLM_RVP_NOCODEC&testcase=verify-kernel-boot-log
[    4.951203] kernel: intel_ish_ipc 0000:00:12.0: ISH loader: request firmware intel/ish/ish_lnlm.bin failed:-2

**Comment by marc-hb** [comment]
The `ish_lnlm.bin failed:-2` error is fixed now

```
block_ish() { ssh ubuntu@"$1".intel.com "printf 'blacklist intel_ish_ipc\n' |
               sudo tee /etc/modprobe.d/blacklist-ish.conf"; }

for hst in jf-lnlm-rvp-sdw-1.jf ba-lnlm-rvp-sdw-01.iind jf-lnlm-rvp-sdw-2.jf ba-lnlm-rvp-sdw-02.iind ..
do echo "$hst"; block_ish "$hst"; done

```

This should really be done with Ansible but good enough for now.

**Comment by spandruvada** [comment]
This firmware intel/ish/ish_lnlm.bin is getting added to Linux firmware. Is this error only appearing on some specific platform?

**Comment by marc-hb** [comment]
> This firmware intel/ish/ish_lnlm.bin is getting added to Linux firmware. 

Too slow! :-)

**Comment by marc-hb** [comment]
> Is this error only appearing on some specific platform?

Yes: LNL with 6.10-rc1: https://github.com/thesofproject/linux/pull/5009

**Comment by spandruvada** [comment]
Need to check FAN error. May be this platform doesn't have FAN support.

**Comment by marc-hb** [comment]
The acpi-fan error is specific to cml-hel-rt5682, totally unrelated. Fixed by `blocklist fan` +
- https://github.com/thesofproject/kconfig/pull/96

**Comment by marc-hb** [comment]
Please re-open if seen again.
