### ISSUE TITLE
[Impovement] Pulseaudio start to be managed by systemd  on Ubuntu 20.04

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#121]
Pulseaudio start to be managed by systemd  on Ubuntu2004, Our current scripts to disable/enable pulseaudio will need improvement. set up the issue to track this change.

**Comment by aiChaoSONG** [comment]
close for now, when we switch to Ubuntu 2004, if need reopen later.

**Comment by marc-hb** [comment]
See related #728

**Comment by marc-hb** [comment]
Duplicate of #91 which has more information
