### ISSUE TITLE
[BUG] PR test fail to .ldc file not found!

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof-test#1216]
**Describe the bug**
Example PR test fail from today 8th July 2024 
https://sof-ci.01.org/sofpr/PR9186/build6326/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-sof-logger

Failure started to be seen after merging
https://github.com/thesofproject/sof/pull/9261

**Comment by andyross** [comment]
Pushed up #1217 to (hopefully) address the CI problems with sof-test not having been updated to the new build behavior.
