### ISSUE TITLE
cleanup and identify test-case log

### ISSUE THREAD

**Issue by Bin-QA** [thesofproject/sof-test#126]
with #123 #125 normally it is not refer the sof-test dump information  
the root reason is TPLG file have too many pipeline,   
so when you catch the case log,  the test case is not run finished  

here need the way to help quickly identify it is not run finish cause this problem  

I have those idea, please help me to confirm which is better:  

1. add special char to let cycle more clean up like:
<br>"---- Text (index/count) begin ----- "
<br>"===== Text (index/count) end ===="
<br>this option can add common function to restrict it
2. private the ANSI color function to let test case dump the cycle begin/end

@xiulipan @fredoh9 @aiChaoSONG @keqiaozhang @libinyang @stripes416

**Comment by aiChaoSONG** [comment]
I vote on "===== Text (index/count) end =====",  Here is the reason: we can only see the colored text in the terminal, if log is stored, we lost the color.
If we have some way to retain the color, of course, we should do this with colors, but seems so so so hard.

**Comment by paulstelian97** [comment]
Why can't both be done? Use colors whenever there is a terminal and ASCII highlighting using "=====" and similar all the time?

**Comment by Bin-QA** [comment]
@paulstelian97 thank you for your advice, that is the good idea
