### ISSUE TITLE
Need one regression case for linux#1762: Ensure system won't hang when sof isn't load successfully.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/sof-test#127]
Need one case to ensure system not hang when sof isn't load successfully.
Eg. 
boot up with sof successfully ->remove firmware file then do system suspend resume
or 
remove firmware file first->do system reboot and system suspend and resume.
or
with firmware file, but remove tplg file to check

**Comment by ClarexZhou** [comment]
will this case be added by test scripts or manually cases?
Because as i remembered,  there is situations "system hang on unit side, but still works by ssh"

**Comment by Bin-QA** [comment]
@ClarexZhou can you add the manual test-case for this issue  
as the automation step, I think it need to many thing to check it

**Comment by ClarexZhou** [comment]
Manual test-case is created in https://github.com/thesofproject/sof-test/pull/131

**Comment by ClarexZhou** [comment]
close for PR #131 is merged
