### ISSUE TITLE
[BUG]Option "-l" cannot be changed in check_capture and check_playback script.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/sof-test#132]
Run with command "/home/ubuntu/sof-test/test-case/check-capture.sh -F -d 100 -f **-l 1** -o /home/ubuntu/sof-test/logs/check-capture/last/wavs -r 1 -t sof-cml-rt711-rt1308-mono-rt715.tplg ", but script still run with 3 loops not one loop.

![Screenshot from 2020-03-19 00-31-02](https://user-images.githubusercontent.com/50347470/77032622-d6c3c880-69df-11ea-988a-bb8a928d19a9.png)

**Comment by aiChaoSONG** [comment]
Please do not use -F and -f together,  -F will iterate all supported formats, while -f only use the first supported format

**Comment by YvonneYang2** [comment]
Tested it with latest master commit:78e300f, issue is gone. Close it.
