### ISSUE TITLE
BUG][CML-SDW]kmod load/unload script need to change

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/sof-test#142]
on  CML RVP SDW
the daily base test  case "Check kmod load/unload" failed,because Module snd_soc_hdac_hdmi is in use by: snd_soc_sof_sdw when remove
http://sof-tcr.sh.intel.com/#/tests/4579f985-3d33-4db0-856a-c250a9c7fefe/detail

<img width="380" alt="Capture" src="https://user-images.githubusercontent.com/56707932/77156932-5d110500-6adb-11ea-9ac4-99576d4011fc.PNG">
need to change the script to remove snd_soc_sof_sdw before remove snd_soc_hdac_hdmi

**Comment by aiChaoSONG** [comment]
https://github.com/thesofproject/sof-test/pull/139 will fix this, and it's waiting Pierre's review

**Comment by Liviali155** [comment]
Fixed closed
