### ISSUE TITLE
check-sof-logger need update

### ISSUE THREAD

**Issue by wenqingfu** [thesofproject/sof-test#143]
https://sof-ci.01.org/sofpr/PR2586/build5392/devicetest/ICL_RVP_HDA/check-sof-logger.sh/check-sof-logger.sh.txt

new printout from https://github.com/thesofproject/sof/pull/2586 will fool the test case with

```
Error: abi version in /etc/sof/sof-icl.ldc file does not coincide with abi version used by logger.
logger ABI Version is 4:2:0
ldc_file ABI Version is 3:14:0
```

apparently, sof-logger isn't working in this case, check-sof-logger should return fail.

**Comment by xiulipan** [comment]
From thesofproject/sof#2586

> Error during conversion should be logged to stderr and to
output file by default

So we could not use output to check if logger is working. We should only use return status.

@aiChaoSONG It would be simple fix for this issue.

**Comment by aiChaoSONG** [comment]
@xiulipan check sof-logger return status is not work, either. because some times, sof-logger not return immediately, didn't figure out why, may because of '-t' option or dsp is suspended?

**Comment by aiChaoSONG** [comment]
I got two solutions here:
- increase minimum file size for compare,  `if [[ $size -lt 100 ]];`
- grep "Error" from generated file.  sof-logger use "Error", Firmware log use "error"
@xiulipan @Bin-QA

**Comment by Bin-QA** [comment]
here refer the other problem:
if `sof-logger` couldn't dump the information, 
so when case refer aplay/arecord will coudln't catch the error/success information  
[func_lib_start_log_collect](https://github.com/thesofproject/sof-test/blob/master/case-lib/lib.sh#L46)

it not just for this case  
so if this case is 'failed'  
refer `aplay/arecord` just use dmesg is enough to trace

**Comment by Bin-QA** [comment]
`grep -i error $tmp_file` after dump, I think this is good for me

**Comment by wenqingfu** [comment]
> * grep "Error" from generated file.  sof-logger use "Error", Firmware log use "error"
>   @xiulipan @Bin-QA

+1

**Comment by xiulipan** [comment]
@aiChaoSONG @Bin-QA Let wait for the fix PR and do a new prod tag today. This would be false positive for all our case now.

> it not just for this case
> so if this case is 'failed'
> refer aplay/arecord just use dmesg is enough to trace ?

This would be a good idea to avoid empty dump. Let try to discuss more about it.

**Comment by aiChaoSONG** [comment]
the fix https://github.com/thesofproject/sof-test/pull/145 is now merged, close this
