### ISSUE TITLE
[BUG][TGL-U]kmod load/unload script need to change

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/sof-test#146]
on TGL-U SDW
Run test case "Check kmod load/unload" failed,because Module snd_soc_rl6231 is in use by: snd_soc_rt1308.
```
skipping snd_soc_rt5682, not loaded
Removing snd_soc_rl6231
rmmod: ERROR: Module snd_soc_rl6231 is in use by: snd_soc_rt1308
2018-01-28 16:00:25 UTC [ERROR] remove modules error
2018-01-28 16:00:25 UTC [INFO] Test Result: FAIL!
```
need to change the script to remove snd_soc_rt1308 before remove snd_soc_rl6231

**Comment by RanderWang** [comment]
yes,  snd_soc_rt1308 is used by 1308 in I2S mode

**Comment by aiChaoSONG** [comment]
@sinahuang Please help to check #152 fix this.

**Comment by sinahuang** [comment]
Issue can't be reproduced with PR #152
