### ISSUE TITLE
Check-kmod-load-unload-after-playback: 25x can  not run

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/sof-test#163]
On GLK 
“line 67: ./check-playback.sh: No such file or directory" when run  ./check-kmod-load-unload-after-playback.sh -l 15
<img width="486" alt="Capture" src="https://user-images.githubusercontent.com/56707932/78236744-0361ff00-750d-11ea-8d53-d7ecefe2c00f.PNG">

**Comment by Liviali155** [comment]
bi-sect result: caused by commit https://github.com/thesofproject/sof-test/commit/e0fae0a4cda8c3077b19300313c86de2dba16947,@Wu, BinX  please check it

**Comment by Bin-QA** [comment]
This issue refer the working directory change, it happen at './' this execute mode  
I will fix it and remove all 'cd' command for the case-lib

**Comment by aiChaoSONG** [comment]
fix merged, close
