### ISSUE TITLE
Trace test is reporting incorrect test results.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof-test#167]
The trace test is to test that the trace output is working. i.e. that DMA trace has valid trace data.

The trace test currently parses the trace data for "error" and reports any "error" strings found as a test fail. This is wrong. This test must not parse the trace log for "error" as it reporting failed trace functionality due to "error" strings in the trace output.

Parsing for "error" is valid for other tests but not this one.

**Comment by aiChaoSONG** [comment]
There is already a fix https://github.com/thesofproject/sof-test/pull/161

**Comment by marc-hb** [comment]
> due to "error" strings in the trace output.

Can someone copy an example?

> Parsing for "error" is valid for other tests 

Parsing should always be avoided when possible. I'm not familiar with this test suite yet but in general searching for kernel errors can be done with just one line:
```
sudo journalctl [ --boot ] --dmesg -p 3
```
and for warnings:
```
sudo journalctl [ --boot ] --dmesg -p 4
```

**Comment by aiChaoSONG** [comment]
This issue is already fixed, we are not detecting error from firmware log anymore.
@marc-hb sorry for misleading you here. the firmware log is not in dmesg, it is extract by sof-logger.

**Comment by marc-hb** [comment]
> Parsing for "error" is valid for other tests but not this one.

Too bad no other test does this.
