### ISSUE TITLE
[new case] check dynamic debug logs

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#173]
With update from https://github.com/thesofproject/linux/pull/1980, we will have dynamic debug feature.
Need a new test case for it.

Example for /etc/modprobe.d/sof-dyndgb.conf is here
https://github.com/thesofproject/linux/pull/1980/commits/bcf28058ef97264a774ec8dc4a3a48bc0a7193da

We need to compare there is indeed difference w/o /etc/modprobe.d/sof-dyndgb.conf

**Comment by fredoh9** [comment]
@xiulipan This is matter of updating sof-dyndbg.conf for all test devices. What test case is required for this. 

Updating /etc/modprobe.d/sof-dyndbg.con will be done when deploying build.

In addition, probably we need to udpate env-check.sh to warn if sof-dyndbg.conf is not available in the system.

**Comment by plbossart** [comment]
@fredoh9 we should check which logs CI depends on, the file I provided initially was more for developer debug and may contains too many traces.

**Comment by fredoh9** [comment]
@plbossart Sure, i will discuss this.
In my understanding CI didn't depends on any debug log, but only error logs. This is more likely to provide more verbose logs for developers. Having said that, your initial version is good to go.

**Comment by fredoh9** [comment]
sof-dyndbg.conf will be downloaded to /etc/modprobe.d/ in every deploy of daily/pr build.
I don't think any new test case is required for this. closing this issue.
