### ISSUE TITLE
[BUG]verify-sof-firmware-load.sh as sub-case meet kernel log file is empty

### ISSUE THREAD

**Issue by Bin-QA** [thesofproject/sof-test#175]
1. target file: /var/log/kern.log is empty, sof-kernel-dump.sh will report bash error  (refer sof-kernel-dump.sh and sof-get-kernel-line.sh)
2. verify-sof-firmware as sub-test to reset `DMESG_LOG_START_LINE`, which will be empty

the original case define use as system boot up to check firmware status, but as sub-case this behavior have the problem

solution:
when verify-sof-firmware load as sub-case, force check from dmesg

**Comment by aiChaoSONG** [comment]
issue is found from https://sof-ci.01.org/linuxpr/PR1897/build3515/devicetest/   CML_RVP_HDA

**Comment by Bin-QA** [comment]
patch merged, close issue
