### ISSUE TITLE
Need one parameter to specify pipeline  for playback/capture and pause/resume scripts

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/sof-test#188]
**Description**
Will always go through all pipelines for playback/capture,and pause/resume scrips.
Need to specify pipeline ID, and fallback to go through all pipelines w/o this parameter.

**Comment by Bin-QA** [comment]
Update for change of source code:  
https://github.com/thesofproject/linux/commits/topic/sof-dev/sound/soc/sof/sof-pci-dev.c

**Comment by ClarexZhou** [comment]
verified with PR#189, -S id:0  or -S id:1,6,0 can works for playback, capture and pause reaume scripts.
