### ISSUE TITLE
file system detect for setup default debugfs for ipc flood test

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#191]
When multiclient architecture changes are merged, https://github.com/thesofproject/linux/pull/1841, defugfs root for
ipc flood test is changed to /sys/kernel/debug/ipc-flood-test.`x`/, where `x` is unique id. debugfs
entries under the root are remained same.

As of today(PR1841 is moving target), this is the changed location.
```
/sys/kernel/debug/sof/sof-ipc-test.0/
/sys/kernel/debug/sof/sof-ipc-test.1/
```

Debugfs file system detect might be required while this pr is getting review. One easy fix is just renaming /sys/kernel/debug/sof/ to /sys/kernel/debug/sof/sof-ipc-test.1/. When this PR is merged.

And as https://github.com/thesofproject/linux/pull/1841 support multiple locations of debugfs for ipc flood test, we can improve more

1. test with /sys/kernel/debug/sof/sof-ipc-test.0/
2. test with /sys/kernel/debug/sof/sof-ipc-test.1/
3. test both client1 and client2 simultaneously. This will be nice to see

The PR i made, https://github.com/thesofproject/sof-test/pull/187, i dropped debugfs location change. I only pushed kmod change required from PR1841

cc:
- #191
- #467
- #847

**Comment by Bin-QA** [comment]
How about use `find /sys/kernel/debug/ -name ipc_flood_count` to catch `ipc_flood_count` file ?

**Comment by fredoh9** [comment]
> How about use `find /sys/kernel/debug/ -name ipc_flood_count` to catch `ipc_flood_count` file ?

Yes, that will work too. But it might hit multiple locations also. (see above description) So take first one should be same as current test.

**Comment by marc-hb** [comment]
@fredoh9 is this still an issue? BTW I noticed that check-ipc-flood is always skipped with IPC4

**Comment by marc-hb** [comment]
There is a symbolic link that is currently in use. Problem solved, @fredoh9 can we close this?

```
root@jf-cml-sku0983-sdw-1:~# file /sys/kernel/debug/sof/ipc_flood_count
/sys/kernel/debug/sof/ipc_flood_count: symbolic link to snd_sof.ipc_flood.0/ipc_flood_count
```

**Comment by fredoh9** [comment]
yes, we can close this
