### ISSUE TITLE
shellcheck: double quotation is required on func_opt_parse_option $*

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#201]
There are a few common shellcheck issues across the test cases.
```
func_opt_parse_option $*
                      ^-- SC2048: Use "$@" (with quotes) to prevent whitespace problems.
                      ^-- SC2086: Double quote to prevent globbing and word splitting.

```

this is a comment from @marc-hb in https://github.com/thesofproject/sof-test/pull/194
If we need to fix this, we need to apply to all.

> The code in and around this functions seems to be a mess of $*, "$*", $@,... but please keep it a consistent mess for now so if something fails it fails the same all across the board :-(
>
> https://mywiki.wooledge.org/Quotes#Expand_argument_lists
> https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

**Comment by aiChaoSONG** [comment]
done a overall cleanup on $* in https://github.com/thesofproject/sof-test/pull/207
