### ISSUE TITLE
[bug][apl]Can not catch sof error trace in  etrace.txt when  CI run failed

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/sof-test#212]
On APL PCM512 
Case "simultaneous-playback-capture-50.sh" and "multiple-pause-resume-25.sh" failed,but there is no any error message in etrace.txt,
When checked in slogger.txt,found sof error trace

Need add "-t" in command when catch sof error trace

details as http://sof-tcr.sh.intel.com/#/tests/7b0db036-2515-454f-bad8-721902a70af1/detail
               http://sof-tcr.sh.intel.com/#/tests/dc4297e6-db95-4eb3-8c2d-2ebf35ee31b6/detail

[7b0db036-2515-454f-bad8-721902a70af1.zip](https://github.com/thesofproject/sof-test/files/4544455/7b0db036-2515-454f-bad8-721902a70af1.zip)
[dc4297e6-db95-4eb3-8c2d-2ebf35ee31b6.zip](https://github.com/thesofproject/sof-test/files/4544457/dc4297e6-db95-4eb3-8c2d-2ebf35ee31b6.zip)

**Comment by Bin-QA** [comment]
@Liviali155 it is kernel refer bug, so sof-logger is no error to output

**Comment by Bin-QA** [comment]
@Liviali155 find 'error' in slogger.txt file

**Comment by Liviali155** [comment]
> @Liviali155 find 'error' in slogger.txt file

Yes,there is error trace in  slogger.txt,the issue is no error trace in etrace.txt,seems can  not catch the error trace separately

**Comment by aiChaoSONG** [comment]
@Liviali155  With `sof-logger -l some.ldc -t`  you get slogger.txt, and with  `sof-logger -l some.ldc ` you get etrace.txt. I have checked the link you provide,  there is only header in etrace.txt, that means our commands for log collection run successfully. 
Please note that some recoverable ERROR in trace log is not present in error log at all, this is allowed, so this is not a sof-test issue.

**Comment by aiChaoSONG** [comment]
@Bin-QA @Liviali155 I do find an issue, please see #213, should fix this.

**Comment by Liviali155** [comment]
> @Liviali155 With `sof-logger -l some.ldc -t` you get slogger.txt, and with `sof-logger -l some.ldc ` you get etrace.txt. I have checked the link you provide, there is only header in etrace.txt, that means our commands for log collection run successfully.
> Please note that some recoverable ERROR in trace log is not present in error log at all, this is allowed, so this is not a sof-test issue.

ok,closed
