### ISSUE TITLE
Enable Cyan module load/unload + suspend-resume tests

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#228]
https://github.com/thesofproject/linux/pull/2138 adds support for system suspend/resume and module load/unload on Cyan.

Can those tests please be re-enabled?
Thanks!

@ranj063 @keyonjie @cujomalainey FYI

**Comment by plbossart** [comment]
@xiulipan @keqiaozhang is this a CI issue instead?

**Comment by aiChaoSONG** [comment]
@plbossart I tried kmod test on one CI cyan device, it cannot pass the 15 iterations' kmod test, I am not sure if we can really enable the case for cyan.
Error message:
```
[ 3432.333395] sof-audio-acpi 808622A8:00: error: firmware boot failure
[ 3432.333443] sof-audio-acpi 808622A8:00: invalid header size 0xffffffff. FW oops is bogus
[ 3432.333449] sof-audio-acpi 808622A8:00: error: unexpected fault 0x90020000 trace 0x00003100
[ 3432.333455] sof-audio-acpi 808622A8:00: error: ipc host -> DSP: pending no complete no raw 0x4000000000003100
[ 3432.333458] sof-audio-acpi 808622A8:00: error: mask host: pending no complete yes raw 0x1
[ 3432.333461] sof-audio-acpi 808622A8:00: error: ipc DSP -> host: pending yes complete no raw 0x90020000
[ 3432.333464] sof-audio-acpi 808622A8:00: error: mask DSP: pending yes complete yes raw 0x3
[ 3432.333468] sof-audio-acpi 808622A8:00: error: failed to boot DSP firmware -5
[ 3432.333583] sof-audio-acpi 808622A8:00: error: sof_probe_work failed err: -5
```

**Comment by plbossart** [comment]
we've already disabled this test, there's a CoreBoot issue.

**Comment by marc-hb** [comment]
@plbossart is the coreboot issue filed somewhere?

**Comment by plbossart** [comment]
> @plbossart is the coreboot issue filed somewhere?

The Google team knows about it, yes. There was a dependency on this bug https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2300765 before a CoreBoot update can be provided. I'll ping Duncan Laurie again.

**Comment by marc-hb** [comment]
> There was a dependency on this bug https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2300765 

It's a pull request but thanks anyway: any reference in the record is infinitely better than nothing.
