### ISSUE TITLE
need top-level script to run all test cases in sequence

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#233]
in test-case I see 29 shell scripts

I have no desire to type anything and wait for each test to be completed.

can we have a top-level script that calls each of the tests in sequence and provides me with a pass/fail result?

@keqiaozhang @marc-hb FYI

**Comment by marc-hb** [comment]
There is already such an internal "test runner" used by sof-ci/jenkins/pr-device-test but it's probably dependent on Jenkins right now. It would be interesting to see if we can isolate the non-Jenkins specific parts and use them outside Jenkins too.

**Comment by plbossart** [comment]
@marc-hb yes my point exactly, we need to stop dependencies on other repos.
This e.g. explains why there is no answer on the issue https://github.com/thesofproject/sof-test/issues/228

Even if we have specific tests for each platform, they need to be part of sof-test and maintained there so that we can truly do unit tests. CI is a framework to run tests, it should not know anything about each test.

**Comment by aiChaoSONG** [comment]
close for we have run-all-tests.sh

**Comment by plbossart** [comment]
reopening: run-all-test.sh does NOT do the same thing as automated tests. We want the same behavior as what is done in CI.

**Comment by marc-hb** [comment]
For instance, CI could switch to (a very futuristic version of) `run-all-tests.sh`, that would address this issue. Just one possible solution, there are other ways to get there.

To be fair @plbossart the current description doesn't even mention CI at all, CI is mentioned only later in the comments. Would you mind editing the description to clarify the (much bigger) scope of this github issue?

**Comment by xiulipan** [comment]
Already have https://github.com/thesofproject/sof-test/blob/master/test-case/run-all-tests.sh
@marc-hb can we close this issue

**Comment by marc-hb** [comment]
We should re-use a proper and flexible test runner but it's not going to happen soon.
