### ISSUE TITLE
improve environment checks for sof-logger

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#234]
sof-logger is required for the tests, but there's no check that it's installed in the 'right' location. Please improve env-check.sh to make sure all the bits and pieces required for tests are properly installed upfront.

**Comment by plbossart** [comment]
Edit: there is a check-sof-logger.sh test. Why can't this be called from env-check?

**Comment by xiulipan** [comment]
@aiChaoSONG @marc-hb any update, I think this feature is almost done along side with lst file check. Please confirm.

**Comment by aiChaoSONG** [comment]
close for #356 merged.
