### ISSUE TITLE
check-ipc-flood: provide better information on fail

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#235]
````
root@upExtreme2:~/sof-test/test-case# ./check-ipc-flood.sh
2020-06-04 19:39:31 UTC [REMOTE_WARNING] ./check-ipc-flood.sh need debug version firmware
2020-06-04 19:39:31 UTC [REMOTE_INFO] Test Result: N/A!
````

what is debug version firmware? can you please provide instructions on what is missing here?

**Comment by xiulipan** [comment]
@plbossart I think the debug version firmware is what it is means. A FW with debug feature enabled.
https://github.com/thesofproject/sof/blob/1d6887f93dc1a29a18cccfeeeee87ac1210b98bd/Kconfig#L166-L170
