### ISSUE TITLE
remove usage of /etc/rc.local in check-reboot.sh

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#237]
There is no reason to change the installed rootfs and muck with distro installation. 
Use your own SOF directory.

**Comment by xiulipan** [comment]
Update the header, @plbossart Do you mean we should add some own file in `/etc/rc0.d/`

**Comment by plbossart** [comment]
you already have /etc/sof for the .ldc file, why do you need to add stuff in a non-SOF directory?

**Comment by xiulipan** [comment]
The check-reboot.sh script is deprecated now and we are working on new test case to test reboot.
