### ISSUE TITLE
stop tests on Ubuntu 18.04

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#238]
we need to stop using Ubuntu 18.04 people, it's obsolete now.

**Comment by fredoh9** [comment]
To be clear, you mean we need to use latest 18.04.x LTS, currently 18.04.04 which is supported by 2023 or latest 20.04 LTS?

**Comment by plbossart** [comment]
we need to use 20.04 LTS and will also probably need to use the latest alsa-lib, alsa-ucm-conf and pulseaudio.

**Comment by aiChaoSONG** [comment]
As all CI device are upgrade to 20.04, close this issue
