### ISSUE TITLE
check-alsabat.sh: remove use of plughw

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#241]
We want to play and record directly at the hw level, not with any conversions done by alsa-lib.
This is wrong and needs to be fixed, it will hide issues or mask conversions.

**Comment by aiChaoSONG** [comment]
@keqiaozhang I think the plughw in alsabat playback is required, because the USB card cannot support all formats and sample rates, but do you think we can remove plughw from alsabat capture?

**Comment by plbossart** [comment]
sorry I don't get the point @aiChaoSONG.

What I meant was that all access to the SOF device should be with hw:

**Comment by keqiaozhang** [comment]
@plbossart , I agree with you, adding plughw is not a wise choice. The reason we use plughw is that the USB sound card only support 1 channel capture and for nocodec mode, we don't use USB sound card for capture, we use the passthrough pipeline directly and it supports 2 channels capture.  To unify the channel count,  we decided to use this workaround. 
I believe there're still have some other reasons, but I can't record right now.
@xiulipan , please help to add here if you still remember.
I will try to refine the test script for alsabat test next.

**Comment by xiulipan** [comment]
@plbossart The plughw here is used because we do not use pulseaudio and we do not know what fmt/channel/rate is supported for our loopback (playback/captur) PCM. So remove plughw is not a option for alsabat test.

**Comment by keqiaozhang** [comment]
I have submitted a PR https://github.com/thesofproject/sof-test/pull/401 to remove plughw for alsabat test.  we can use tplgreader to get the fmt/channel and rate for playback PCM, but for USB sound card(used to capture the loopback data), it only support S16_LE/1 channel, so I just specified format and channel for USB sound card.

**Comment by xiulipan** [comment]
@keqiaozhang We also have headset capture test, you can only removed plug from one side.

**Comment by xiulipan** [comment]
merged https://github.com/thesofproject/sof-test/pull/554 @keqiaozhang @plbossart can we close this issue.

**Comment by keqiaozhang** [comment]
PR#554 is merged, this issue can be closed.
