### ISSUE TITLE
sof-dump-status.py: don't hardcode PCI device ID

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#244]
You can get the PCI ID by looking at 

more /sys/bus/pci/devices/0000\:00\:1f.3/device 
0x9dc8

for APL/GPL it's a different value but the same idea.

Never ever duplicate values!

**Comment by xiulipan** [comment]
@plbossart I did not see any hardcode PCI device ID. We only used the SOF PCI driver map for the platform name
