### ISSUE TITLE
fix firmware location for open platforms

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#246]
For some platforms such as Up2 and Chromebooks, the firmware location is in /lib/firmware/intel/sof/community

see sound/soc/sof/sof-pci-dev.c

**Comment by aiChaoSONG** [comment]
@plbossart This is not a problem now, we uses the same match mechanism as the kernel does to identify community boards and product boards, and then use different FW folder. see `sof-dump-status.py line 437`

**Comment by aiChaoSONG** [comment]
close for issue already fixed.
