### ISSUE TITLE
verify-sof-firmware-load.sh does not do what it says

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#247]
the script only checks the firmware version in the firmware, it does not test for a successful load and boot.

Either this is called dump-sof-firmware-version.sh or someone adds a true check that the DSP did boot.

**Comment by aiChaoSONG** [comment]
@plbossart Before SOF logs are reduced in the kernel, we use "firmware boot complete" to detect FW load status, but after logs are reduced, this method never works. We have to use proper keyword from dmesg to know FW load status.  Firmware version is sent from FW side with IPC, so it can be used to detect FW load status too.

**Comment by plbossart** [comment]
@aiChaoSONG you can get the same logs by adding dynamic debug on the platform, e.g. copy the attached file as /etc/modprobe.d/sof-ddebug.conf
[ddebug.txt](https://github.com/thesofproject/sof-test/files/4794228/ddebug.txt)

**Comment by xiulipan** [comment]
@aiChaoSONG I think we deploy the `sof-ddebug.conf` on all DUTs, please confirm if we can close this issue now.

**Comment by aiChaoSONG** [comment]
@xiulipan Yes, we will deploy sof-dyndbg.conf along with kernel deploying

**Comment by xiulipan** [comment]
@plbossart Could we close the issue as the  `sof-dyndbg.conf` in now enabled on all DUTs.
