### ISSUE TITLE
[bug] current capture related scripts command isn't write KWD pipline command

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/sof-test#259]
such as
https://github.com/thesofproject/sof-test/blob/master/test-case/check-capture.sh

only using "arecord -D$dev -r $rate -c $channel -f $fmt_elem -d $duration $file -v -q", this command isn't for kwd pipline.
e.g Dhw:0,7 in sof-hda-generic-4ch-kwd.tplg

**Comment by aiChaoSONG** [comment]
@ClarexZhou For KWD pipeline, if we run arecord, there will be ipc error, is this fixed now?

**Comment by ClarexZhou** [comment]
For KWD pipline, shouldn't use normal arecord command, only work use command with "-M -N", like ``` arecord -Dhw:0,$device_id -M -N -f s24_le -r 16000 -i -vvv -c2 --buffer-size=68000 ./tmp.wav```,  is it able to identify KWD pipline currently?  or should KWD pipline name be changed to some think specific? @xiulipan  Do you have any ideas about this?

**Comment by aiChaoSONG** [comment]
@ClarexZhou Idea is good, but WHO is going to trigger KWD in CI?

**Comment by xiulipan** [comment]
Close as we have KWD test now. We can also filter KWD pipeline.
