### ISSUE TITLE
ignore_str to have root cause or known issue description

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#261]
There is array of ignoring error message.
https://github.com/thesofproject/sof-test/blob/master/tools/sof-kernel-log-check.sh#L6

This error message was captured but it is known problem. But there is no description why this is safely ignored.
`ignore_str="error: debugfs write failed to idle -16|error: status|iteration [01]"`

@marc-hb added comments, https://github.com/thesofproject/sof-test/pull/258

Ignoring errors is very dangerous and should be carefully reviewed and extensively documented. At the very least this code should be changed to something like:
```shell
# because blabla, see bug 1234
ignore_str="$ignore_str"'|error: debugfs write failed to idle -16'
# because blabla, see bug 5678
ignore_str="$ignore_str"'|error: status'
```

**Comment by marc-hb** [comment]
I tig blamed the history of that `ignorestr` list:

- The `iteration [01]` exclusion was added by d238c48cf which mentions issue #43
- `error: status` was added by commit 50f6ccf895c5 . It mentions https://github.com/thesofproject/linux/pull/1676
- `debugfs write failed...` was added by initial commit b3b7d8df9c84 which is unfortunately not specific.

@aiChaoSONG could you implement and test this line split? For the `debugfs write...` line leave a `# TODO` for now.

@xiulipan, @plbossart  do you know why this this `debugfs write...` error must be ignored?

**Comment by aiChaoSONG** [comment]
@marc-hb I have no idea why `debugfs write..` is added, it is far before I joined CI, but some error string in ignore_str is deprecated. I will try to clean up and split ignore_str after Dragon Boat Holiday.

**Comment by aiChaoSONG** [comment]
@Bin-QA Could you please help to find the reason for each ignore_str? though Marc gives some hint, but from the releated commit's message, It's really hard to know the reason, because the message is not clear.

**Comment by aiChaoSONG** [comment]
WIP PR: https://github.com/thesofproject/sof-test/pull/268
