### ISSUE TITLE
[TGL][BUG]Module can't load up successfully after doing module unload/load test.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/sof-test#264]
**Describe the bug**
Module can't load up successfully after doing module unload/load test. 

**To Reproduce**
1.Boot up system successfully
2. cd sof-test/test-case/
3 Run "./check-kmod-load-unload.sh -l 2" (https://github.com/thesofproject/sof-test/blob/master/test-case/check-kmod-load-unload.sh)

**Reproduce rate**
5/5

**Expected result**
Module should load up successfully when doing module load/unload test.

**Actual result**
Module can't load up successfully after doing module load/unload test.

**Environment**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+ PR#2184 for wov S0i2 
+ [0001-hack-hack-98373-for-feedback-data-validation.patch.txt](https://github.com/thesofproject/sof/files/4812034/0001-hack-hack-98373-for-feedback-data-validation.patch.txt)

For volteer:
+ revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a   for volteer
+ revert  d4b41f8bb
+ revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d  for volteer
https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc2 commit: b36dabe4
+ revert e35e91de652e06183c51ecc9814e7165f780c116
+ PR 3069
FW:
https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc2 commit: b36dabe4
+ revert e35e91de652e06183c51ecc9814e7165f780c116
+ PR 3069
TPLG:sof-tgl-max98373-rt5682.tplg
Platform:Chromebook with codec 98373 in I2S mode.
[dmsg.log](https://github.com/thesofproject/linux/files/4818138/dmsg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4818139/sof_trace.log)

**Comment by ClarexZhou** [comment]
close for sof_insert.sh already updated with sudo modprobe snd_soc_rt5682_i2c
