### ISSUE TITLE
Include KWD test into sof-test

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof-test#270]
This is created to track the status of adding automation KWD test into CI. It includes subtasks as below:

1. KWD pipelines/PCMs identify from the topology binary files.

2. Deploy DMIC injector on DUT for automation test via playing typical .wav file onto the injector.

3. Add KWD related test cases.

**Comment by keyonjie** [comment]
#1 is done by Chao.
#2 injector connection to TGL RVP is done by Keqiao, typical .wav file is under investigation.
Xiuli is working on adding KWD pipelines to sof-tgl-nocodec.m4, after that we can implement #3.

**Comment by mengdonglin** [comment]
The test case is done. So close this issue here.

**Comment by mengdonglin** [comment]
sof-hda-generic-kwd.m4 enabled WoV test in RVP with HD-Audio codecs.
