### ISSUE TITLE
Add S0ix test to sof-test

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof-test#273]
This is created to track the status of adding automation S0Ix test into CI. It includes subtasks as below:

1. figure out the suitable platforms (e.g. TGL RVP with correct stepping silicon) for S0ix test.
2. figure out the suitable recipe (e.g. the sof topic/sof-dev kernel might be not suitable) for S0ix test.
3. Add S0ix related test cases.

**Comment by marc-hb** [comment]
wontfix
