### ISSUE TITLE
Do not use 'snd-sof-pci' in scripts

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#287]
We can't have such scripts, they don't work with snd_sof_acpi !

````
test-case/check-kmod-load-unload.sh:    # pulseaudio deamon will detect the snd_sof_pci device after 3s
test-case/check-kmod-load-unload.sh:    # so after 2s snd_sof_pci device will in used status which is block current case logic
test-case/check-kmod-load-unload.sh:    # here the logic is to check snd_sof_pci status is not in used status, the max delay is 10s
test-case/check-kmod-load-unload.sh:        [[ "X$(awk '/^snd_sof_pci/ {print $3;}' /proc/modules)" == "X0" ]] && break
````

**Comment by fredoh9** [comment]
For ACPI dev, this is just adding 10 second delay. As we already disabled pulseaudio, we can remove this safely.

**Comment by fredoh9** [comment]
I removed above lines, I tested with ICL and BSW which have disabled pulseaudio. As expected, kmod test was working fine. And I can see ICL finishes 2-3 seconds faster, BSW finishes a lot faster.
