### ISSUE TITLE
rtcwake error during suspend / resume tests

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#304]
Sometimes suspend-resume tests fail with an rtcwake error:
```
rtcwake: /dev/rtc0: unable to find device: Device or resource busy
```
This shouldn't be considered an SOF failure. A retry might help.

**Comment by mengdonglin** [comment]
This issue is also tracked by https://github.com/thesofproject/linux/issues/2495. But it's not a test case issue.
