### ISSUE TITLE
check-suspend-resume.sh should verify, that SOF is running

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#305]
During a daily test one of kernel module loading and unloading scripts left SOF unloaded. After that check-suspend-resume.sh ran and reported success, because the system was able to suspend and resume with no errors, even though SOF wasn't even present. The script should check that SOF is active before beginning the process.

**Comment by marc-hb** [comment]
P1 because any "green failure" (false negative without the double negation) should be P1

**Comment by plbossart** [comment]
There is a dmesg trace 'probe complete' that can be used.

	dev_dbg(dev, "Completing SOF PCI probe");

I just added the same for ACPI, that should help detect that the driver loaded ok. https://github.com/thesofproject/linux/pull/2338
In addition the script can check for the presence of a card, there can be cases where SOF probes but the card is not registered, and the error is squelched by the driver core.

**Comment by lyakh** [comment]
@plbossart I think there's a problem with that too. I've seen at least one test in CI where the test sequence was started when the system has already been running for some time, so, the kernel message buffer has already discarded SOF probing messages. You can see such cases when some of the first few tests fail. Can we not use some /proc or /sys or /dev or aplay -l test instead?

**Comment by marc-hb** [comment]
We're working on replacing `dmesg` with `journalctl [ --boot ] [ --dmesg ] [ etc.]`

**Comment by plbossart** [comment]
> @plbossart I think there's a problem with that too. I've seen at least one test in CI where the test sequence was started when the system has already been running for some time, so, the kernel message buffer has already discarded SOF probing messages. You can see such cases when some of the first few tests fail. Can we not use some /proc or /sys or /dev or aplay -l test instead?

Goodness. I hope the test devices reboot and only do a modprobe snd-soc-pci when the tests are actually enabled? In other words we don't want to probe the drivers at boot, otherwise yes the logs might have been erased for an odd reason.

**Comment by marc-hb** [comment]
>  In other words we don't want to probe the drivers at boot, otherwise yes the logs might have been erased for an odd reason.

I'm not a fan of loading the drivers at boot either (I've been told it's closer to the "real-world") but `journalctl` typically keeps hundreds of megabytes of logs over many days and can be extended if needed so that should not be a problem anymore once the transition is finished.

**Comment by marc-hb** [comment]
> After that check-suspend-resume.sh ran and reported success, because the system was able to suspend and resume with no errors, even though SOF wasn't even present. The script should check that SOF is active before beginning the process.

We have a `check-suspend-resume-with-playback`, @lyakh is that enough?

**Comment by mengdonglin** [comment]
Close this issue, because
- Test case check-suspend-resume-with-playback checks SOF presence after system resumes. 
- CI is switch to use journalctl, so the early log will be kept in disc storage and will not be lost.
