### ISSUE TITLE
multiple-pipeline-{capture,playback}.sh are broken

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#324]
The multiple-pipeline-playback.sh and multiple-pipeline-capture.sh scripts are broken, they do nothing. They check `$PIPELINE_COUNT` before parsing topology by calling `func_pipeline_export`

**Comment by plbossart** [comment]
@lyakh do you mean to say that this line is wrong?

````
[[ $PIPELINE_COUNT -gt ${OPT_VALUE_lst['c']} ]] && max_count=${OPT_VALUE_lst['c']} || max_count=$PIPELINE_COUNT
f
````

I must say I have zero understanding of these scripts.

**Comment by lyakh** [comment]
> @lyakh do you mean to say that this line is wrong?
> 
> ```
> [[ $PIPELINE_COUNT -gt ${OPT_VALUE_lst['c']} ]] && max_count=${OPT_VALUE_lst['c']} || max_count=$PIPELINE_COUNT
> f
> ```
> 
> I must say I have zero understanding of these scripts.

@plbossart it isn't about the contents of that line, it's about when it is executed, respectively when the `$PIPELINE_COUNT` variable is evaluated. Evaluating it before it is set makes no sense and it is only set in `func_pipeline_export()`

**Comment by aiChaoSONG** [comment]
@lyakh This is fixed by https://github.com/thesofproject/sof-test/pull/380, thanks.  let's close this
