### ISSUE TITLE
add option to limit run-all-tests.sh to CI tests

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#331]
run-all-tests.sh takes nearly 1.5 hours on my SoundWire device. It's fine for daily tests, not great for a quick check before sending a PR.

Can we add an option and split the test cases in what is used by CI, and what is used by daily tests?

@marc-hb will tell me we need a 'test runner' but all I care about for now is something that reproduces CI and daily tests, as is.

**Comment by marc-hb** [comment]
I have a local commit that reduces the duration to 5-7 minutes on my Up2. It does that by merely changing the --loop, --count and --round parameters. @bardliao can you explain how you chose the default values?

> Can we add an option and split the test cases in what is used by CI, and what is used by daily tests?

Having two sets of tests if also something I've done locally, I can easily combine the two and make that a command line option and submit it but I need to know what are these two exact subsets and their parameters. @bardliao , @xiulipan can you share that information?

**Comment by bardliao** [comment]
> I have a local commit that reduces the duration to 5-7 minutes on my Up2. It does that by merely changing the --loop, --count and --round parameters. @bardliao can you explain how you chose the default values?

No, the script is from our QA folks and I don't know who is the author. 

> 
> > Can we add an option and split the test cases in what is used by CI, and what is used by daily tests?
> 
> Having two sets of tests if also something I've done locally, I can easily combine the two and make that a command line option and submit it but I need to know what are these two exact subsets and their parameters. @bardliao , @xiulipan can you share that information?

**Comment by mengdonglin** [comment]
@marc-hb Are you working on this feature?

**Comment by marc-hb** [comment]
I have not been working on it but I've been thinking about it. What is needed here is a configurable test runner and we should try to re-use an existing one for a change instead of re-inventing one; this is a very standard concept.

After a quick search I found https://github.com/bats-core/bats-core and it looks like it would work and support test selection but I'm not sure it would be convenient to manage test parameters.

**Comment by xiulipan** [comment]
@aiChaoSONG I think we have enabled this feature, right? please confirm and close the issue.

**Comment by aiChaoSONG** [comment]
I think @marc-hb has add  loop options, 9853627,  The very_short_tests(-l 1) option just work like PR test plan.

**Comment by marc-hb** [comment]
@plbossart you filed this; is the short loop option good enough for you?
