### ISSUE TITLE
Add some tests with S24_LE and S32_LE

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#332]
It seems that the tests only rely on S16_LE, which is only a small part of the supported formats.
Let's add S24 and S32_LE tests for playback.
For capture this might be the opposite, IIRC the DMICs can only support S32_LE.

**Comment by aiChaoSONG** [comment]
test cases for playback and capture with S24_LE and S32_LE are added to PR test. The format(s) used to playback/capture are extracted from PCM capabilities, so we can test capture, too.

**Comment by aiChaoSONG** [comment]
close for check-playback-all-formats and check-capture-all-formats are added
