### ISSUE TITLE
Ignore iwlwifi, thermal errors on Dell laptop

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#343]
Need to filter out non audio errors in Dell laptop.

```
[    0.713554] tpm tpm0: tpm_try_transmit: send(): error -5
[    0.787321] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    0.787322] cfg80211: failed to load regulatory.db
[    1.281146] EXT4-fs (nvme0n1p6): re-mounted. Opts: errors=remount-ro
[    1.290704] usb 2-3: Enable of device-initiated U1 failed.
[    1.291010] usb 2-3: Enable of device-initiated U2 failed.
[    1.444017] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-56.ucode failed with error -2
[    1.444814] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-55.ucode failed with error -2
[    1.444863] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-54.ucode failed with error -2
[    1.444874] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-53.ucode failed with error -2
[    1.444882] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-52.ucode failed with error -2
[    1.444890] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-51.ucode failed with error -2
[    1.444898] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-50.ucode failed with error -2
[    1.444936] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-49.ucode failed with error -2
[    1.446871] iwlwifi 0000:00:14.3: Direct firmware load for iwl-debug-yoyo.bin failed with error -2
[    1.631431] thermal thermal_zone10: failed to read out thermal zone (-61)
```

**Comment by fredoh9** [comment]
@plbossart 
For better filtering, I need sof-test logs for this, fail/errors in booting doesn't fail the test cases. Especially I need testing logs with

- check-runtime-pm-status.sh
- check-kmod-load-unload.sh

Or let me allow SSH into the device once.

**Comment by plbossart** [comment]
@fredoh9 the errors were copy/pasted from the sof-test logs. This is on a Dell CML-U w/ SoundWire which is NOT in CI for far.

**Comment by marc-hb** [comment]
The iwlwifi are warnings, not errors. We should really stop screen-scraping logs and use error levels some day.

**Comment by plbossart** [comment]
> The iwlwifi are warnings, not errors. We should really stop screen-scraping logs and use error levels some day.

maybe, but this is real today.

````
2020-08-26 22:04:29 UTC [ERROR] Caught dmesg error
===========================>>
Aug 26 17:00:21 plb-olympic kernel: [ 5456.059737] iwlwifi 0000:00:14.3: Microcode SW error detected. Restarting 0x0.
<<===========================
2020-08-26 22:04:29 UTC Sub-Test: [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2020-08-26 22:04:29 UTC Sub-Test: [ERROR]  main()  @  ./multiple-pause-resume.sh
2020-08-26 22:04:30 UTC Sub-Test: [ERROR] sof-logger was already dead
2020-08-26 22:04:31 UTC Sub-Test: [INFO] Test Result: FAIL!
````

**Comment by plbossart** [comment]
Actually @marc-hb you're right the filters are broken.

We get an error on ICL RVP (and others) just because we will detect 'panic' in the following trace

````
[  345.962670] sof-audio-pci 0000:00:1f.3: status = 0x00000000 panic = 0x00000000
````

we really only want to track errors, then look for such keywords.
Meh.

**Comment by plbossart** [comment]
Can someone please explain to me what on earth this script is supposed to do

````bash
begin_line=${1:-1}

# confirm begin_line is number, if it is not the number, direct using dmesg
[[ "${begin_line//[0-9]/}" ]] && begin_line=0
[[ "$begin_line" -eq 0 ]] && cmd="dmesg" || cmd="sed -n '$begin_line,\$p' /var/log/kern.log"

#echo "run $0 with parameter '$*' for check kernel message error"

if [ "$ignore_str" ]; then
    err=$(eval $cmd|grep 'Call Trace' -A5 -B3)$(eval $cmd | grep -E "$err_str"|grep -vE "$ignore_str")
else
    err=$(eval $cmd|grep 'Call Trace' -A5 -B3)$(eval $cmd | grep -E "$err_str")
fi

````

**Comment by marc-hb** [comment]
> maybe, but this is real today.

Agreed, happy to merge #343 except for the parentheses `( )` concern.

> Can someone please explain to me what on earth this script is supposed to do. 

The "begin_line" logic separates logs from consecutive runs.

> fixed  to use dmesg --level=err,warn

`journalctl -p warning --since=...` for two reasons:
- no ring buffer exhaustion issue
- user space errors matter too

See initial attempts in PR #262. Bin-QA moved on but I believe @fredoh9 has been resuming this (he's on vacation now)

**Comment by aiChaoSONG** [comment]
@plbossart I saw your patch https://github.com/thesofproject/sof-test/pull/354, I guess you already figured out what it does.
- Before running a test case, record log point of /var/log/kern.log with `func_lib_setup_kernel_last_line`
- After running the test case, collect log from the recorded log point with `sof-kernel-log-check.sh "$KERNEL_LAST_LINE"`

**Comment by plbossart** [comment]
> @plbossart I saw your patch #354, I guess you already figured out what it does.
> 
> * Before running a test case, record log point of /var/log/kern.log with `func_lib_setup_kernel_last_line`
> * After running the test case, collect log from the recorded log point with `sof-kernel-log-check.sh "$KERNEL_LAST_LINE"`

Yes, but this is not so good. We need to use a *timestamp*, that way we can filter with whatever level we want. Using the raw line number is a major limitation.

**Comment by marc-hb** [comment]
#354 was abandoned by @plbossart , I'm "rescuing" the filters part of it in #362 , please review.

**Comment by mengdonglin** [comment]
#362 merged, close this issue
