### ISSUE TITLE
kmod-load-unload shouldn't exit with modules unloaded

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#351]
If an error is detected when unloading kernel modules (see e.g. https://github.com/thesofproject/linux/issues/2334) the check-kmod-load-unload.sh script exits immediately with modules unloaded, so no further testing is possible. If a proposed policy is implemented where the tested system is rebooted after a failure, this would be fixed. Otherwise an attempt should be made to re-load the modules after the error.

**Comment by marc-hb** [comment]
In https://github.com/thesofproject/linux/issues/2334 @plbossart suggested we try multiple times and count the number of errors.

I looked at the code it should be doable but please first please help review the simple shellcheck cleanup in #368

**Comment by aiChaoSONG** [comment]
It is not easy to fix it in the script, because kmod test touched kernel, and it is hard to make sure the kernel module can be reloaded properly, and the HW status is status, so current solution is 'when kmod test falied, we will reboot and continue test'
