### ISSUE TITLE
Fix exit status of script

### ISSUE THREAD

**Issue by Bin-QA** [thesofproject/sof-test#37]
in  https://github.com/thesofproject/sof-test/pull/11 I find we have some error exit  
```
man bash :
All builtins return an exit status of 2  to  indicate  incorrect usage, 
generally invalid options or missing arguments.
```

We already define  at [exit function](https://github.com/thesofproject/sof-test/blob/master/case-lib/hijack.sh#L51)
```
0: pass
1: fail
2: skip
other: fail
```
but don't document it & fix some exit code in the script

**Comment by aiChaoSONG** [comment]
fixed and close
