### ISSUE TITLE
i915 0000:00:02.0: [drm] ERROR TC cold [un]block failed in check-suspend-resume.sh 

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/sof-test#374]
suspend-resume test was failed by these error

```
[ 7854.607440] i915 0000:00:02.0: [drm] *ERROR* TC cold unblock failed
[ 7854.616848] i915 0000:00:02.0: [drm] *ERROR* TC cold block failed
[ 7854.616910] i915 0000:00:02.0: [drm] *ERROR* TC cold unblock failed
[ 7854.616926] i915 0000:00:02.0: [drm] *ERROR* TC cold block failed
[ 7854.616996] i915 0000:00:02.0: [drm] *ERROR* TC cold unblock failed
[ 7854.617011] i915 0000:00:02.0: [drm] *ERROR* TC cold block failed
[ 7854.617097] i915 0000:00:02.0: [drm] *ERROR* TC cold unblock failed
[ 7854.617116] i915 0000:00:02.0: [drm] *ERROR* TC cold block failed
[ 7854.617175] i915 0000:00:02.0: [drm] *ERROR* TC cold unblock failed
[ 7854.631418] atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
[ 7855.007595] atkbd serio0: Failed to enable keyboard on isa0060/serio0
[ 7855.020982] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 7855.020999] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG

```

**Comment by marc-hb** [comment]
For now this bug has zero configuration and version information in the description, neither about hardware, firmware or software. Please add some.

There are three different and likely unrelated parts in this log.

The `sof-audio-pci` messages seem harmless and hopefully unrelated.

The `atkbd serio0` can hopefully be ignored. Can you try disabling legacy mouse/legacy keyboard support in the BIOS and see if it goes away?

The Type-C errors are more worrying and could affect test results if they rely on some USB or Display+audio device. Can you confirm there is no such dependency? They should also be reported to the i915 team with of course the exact kernel version.

Hopefully none of these errors leave the kernel in a bad state.

**Comment by marc-hb** [comment]
https://cgit.freedesktop.org/drm/drm/log/?h=05e31dd78e26 looks relevant:
```
    05e31dd78e26 imre.deak@intel.com // drm/i915/tgl: Fix TC-cold block/unblock sequence
    b302a2e68807 imre.deak@intel.com // drm/i915/tgl: Make sure TC-cold is blocked before enabling TC AUX power wells
```
It believe this is queued for 5.10, not for 5.9.

Again this bug needs more information.

**Comment by kv2019i** [comment]
The bug is indeed missing some critical information (link to example failure, platform used), but these TC DRM errors can be put to ignore list.

**Comment by RanderWang** [comment]
it happens on tgl rvp

**Comment by marc-hb** [comment]
thanks, the very least needed here is the kernel version.

**Comment by RanderWang** [comment]
daily test image of everyday recently.  5.9.0-rc7+ or newer

**Comment by RanderWang** [comment]
it is fixed by kernel now

**Comment by RanderWang** [comment]
sorry， I got different status.  @RuiqingX , Did you change FW ?  the default FW is CAVS FW.

**Comment by marc-hb** [comment]
> it is fixed by kernel now

Can `ignore_str` addition 589920e6ee83 be reverted/removed then? Is that why you re-opened this?

See guidelines in commit 9c55f30647cdd8d

**Comment by aiChaoSONG** [comment]
@marc-hb There is `*` in the error message, but markdown has eaten it,  So the fix https://github.com/thesofproject/sof-test/commit/589920e6ee83dfb7e8aae7d3ca7f5ba55dd472af, cannot work, and @RuiqingX update the fix to #496

**Comment by xiulipan** [comment]
@RanderWang can you try to upload the original log file. I think we may got some format issue here.

**Comment by RanderWang** [comment]
[kernel.log](https://github.com/thesofproject/sof-test/files/5528840/kernel.log)
@xiulipan  please check this log

**Comment by marc-hb** [comment]
I downloaded and looked at this log. There is no need to look at this log, it has no information that the description doesn't already have.

I have not tested it but the regex fix in #496 looks correct. gowever #496 is missing a commit message.

Please test #496 locally with `fake_kern_error()`.

If  589920e had been tested with `fake_kern_error()` then we would not be spending so much time discussing it again.

If all code changes submitted were actually tested we would save a lot of time.

**Comment by RanderWang** [comment]
it is fixed

**Comment by marc-hb** [comment]
What is fixed? #496 is not merged.

**Comment by marc-hb** [comment]
> The atkbd serio0 can hopefully be ignored. Can you try disabling legacy mouse/legacy keyboard support in the BIOS and see if it goes away?

Disabling PS/2 in BIOS does get rid of this irrelevant error, @XiaoyunWu6666 confirm?

**Comment by XiaoyunWu6666** [comment]
@marc-hb  Recently no 'atkbd serio0: Failed to enable keyboard on isa0060/serio0' error occurred or caused cases to fail . So I tend to believe that this can help get rid of this irrelevant error.
I'll keep an eye on it
