### ISSUE TITLE
[BYT][NOCODEC] alsa-bat check-alsabat-headset-playback.sh FAIL

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#379]
tracking https://sof-ci.01.org/linuxpr/PR2396/build4392/devicetest/

No idea why this happens. Our 'all green' status for CI devices lasted only a couple of hours.
@lgirdwood @lyakh FYI, not sure if anything changed at the firmware level?

**Comment by kv2019i** [comment]
More cases, but now reported as TIMEOUTs and not FAILS in CI report:
https://sof-ci.01.org/linuxpr/PR2474/build4586/devicetest/
https://sof-ci.01.org/linuxpr/PR2476/build4589/devicetest/

... with TIMEOUT, there is no wave file to investigate, but alsabat console output looks identical to this bug.

**Comment by marc-hb** [comment]
From https://github.com/thesofproject/sof-test/pull/430#pullrequestreview-507683976
> The test that I'm developing shows that on BYT the channels get swapped randomly

**Comment by plbossart** [comment]
oh, now that I think of it, I don't know if there's actually a way to control the channel order.

The fsync phase defines which channel is being played/captured, and if we enable the capture at any moment we could very well select the current fsync, which means either right or left get captured first. I don't know if there's a way to enable a capture on a predictable phase?

**Comment by marc-hb** [comment]
New `[BUG] BYT: Random stereo channels swaps happen with sof-byt-nocodec.tplg` https://github.com/thesofproject/sof/issues/3520

**Comment by kv2019i** [comment]
One case where BYT alsabat fails with audio produced (no timeout), but the wave file is clipping. Wrong gains in DUT or test setup?
https://sof-ci.01.org/linuxpr/PR2518/build4747/devicetest/

**Comment by xiulipan** [comment]
any update? @thesofproject/test-maintainers I think we have update the alsa-bat test with wavtool and new hardware.

**Comment by mengdonglin** [comment]
The logic of alsabat may need to modify: sometimes there can be peak in the side lope, and this is acceptable for human.

**Comment by mengdonglin** [comment]
Lower the priority as this failure hasn't been observed recently.

**Comment by marc-hb** [comment]
assumed fixed
