### ISSUE TITLE
[CML] ignore non-audio failure caused by mei_me module

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#389]
In the test of topic/sof-dev + stable-v1.6, we observed a false failure caused by mei_me module: `[ 6965.377054] mei_me 0000:00:16.4: hw_reset failed ret = -62`, this message should be filter out.

```
kernel: [ 6965.377054] mei_me 0000:00:16.4: hw_reset failed ret = -62
kernel: [ 6965.377099] mei_me 0000:00:16.4: unexpected reset: dev_state = ENABLED fw status = A4004103 00000000 00000000 00000000 00000000 00000000
```

The daily test report id is 457

**Comment by aiChaoSONG** [comment]
In daily report 473, similar issue is observed on ICL_RVP_HDA and CML_RVP_SDW, `[ 6733.766202] mei_me 0000:00:16.0: hw_reset failed ret = -62`, but with a different ID.

**Comment by kv2019i** [comment]
Still happening with CML_RDP_SDW. Made a patch to sof-test:
https://github.com/thesofproject/sof-test/pull/463

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR3774/build421/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=check-suspend-resume-5

````
===========================>>
[ 1160.148503] kernel: mei_me 0000:00:16.0: hbm: add client: state mismatch, [1, 3]
[ 1160.148507] kernel: mei_me 0000:00:16.0: mei_irq_read_handler ret = -71, state = 1.
[ 1160.149128] kernel: mei_me 0000:00:16.0: mei_irq_read_handler ret = -71, state = 1.
<<===========================
````

**Comment by marc-hb** [comment]
Please re-open if observed again.
