### ISSUE TITLE
Ignore i2c_hid i2c-DELL0955:00 error on Dell CML laptop

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof-test#396]
Please over unrelative error of i2c_hid i2c-DELL0955:00.

Fake failure observed in testing with SOF v.16 FW and linux-stable-5.8.10 kernel:
```
2020-09-21 08:08:48 UTC [ERROR] Caught dmesg error
===========================>>
Sep 21 08:06:27 sh-cml-mantis-hda-01 kernel: [    6.496237] i2c_hid i2c-DELL0955:00: failed to set a report to device.
<<===========================
2020-09-21 08:08:48 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
```

**Comment by marc-hb** [comment]
Can you please provide a longer trace? Including some unrelated context before and after: this proves nothing related was ommitted.

If you're not sure please link to some CI test report and I'll try to do it.
