### ISSUE TITLE
check-alsabat-headset-playback.sh fails occasionally for CML_RVP_SDW

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof-test#407]
We have occasional failures in this test. The test result is TIMEOUT so the wave output is not shown in failing cases. Logs don't show anything that pops up:

https://sof-ci.01.org/linuxpr/PR2456/build4540/devicetest/
https://sof-ci.01.org/linuxpr/PR2462/build4568/devicetest/
https://sof-ci.01.org/linuxpr/PR2462/build4546/devicetest/

**Comment by keqiaozhang** [comment]
This issue should be fixed by https://gitlab.devtools.intel.com/sof-ci/sof-framework/-/merge_requests/105.
Will keep this issue open and continue to monitor the results for a while.

**Comment by mengdonglin** [comment]
@keqiaozhang Can we close this issue now?

**Comment by keqiaozhang** [comment]
I think so, this issue is not reproducible for now.
