### ISSUE TITLE
verify-sof-firmware-load.sh fails once in a while

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#413]
This is an example on GLK but i found this in different platform also.

https://sof-ci.01.org/linuxpr/PR2297/build4635/devicetest/

```
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: ipc: DSP is ready 0x70000000 offset 0x81000
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: Firmware info: version 1:5:0-9e9ae
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: Firmware: ABI 3:18:0 Kernel ABI 3:17:0
```

Looks SOF version information is there. Not sure what cause this failure.

**Comment by marc-hb** [comment]
@fredoh9 is #427 a duplicate of #413? If yes please close this one as #427 has more information.

**Comment by xiulipan** [comment]
ping for update

**Comment by marc-hb** [comment]
@fredoh9 ?

**Comment by fredoh9** [comment]
I haven't seen this for a long time. We can close this.
