### ISSUE TITLE
"Cannot find the sof audio version" fake failure in verify-sof-firmware-load.sh in daily test

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof-test#427]
The test case failed to find audio version in the log and reported a fake failure: 
```
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: ipc: DSP is ready 0x70000000 offset 0x81000
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: Firmware info: version 1:5:0-6e98d
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: Firmware: ABI 3:17:0 Kernel ABI 3:17:0
--
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: tplg: 1 hw_configs found, default id: 2!
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: tplg: config DMIC0 driver version 1
4月 01 17:23:46 sh-glk-bob-da7219-03 kernel: sof-audio-pci 0000:00:0e.0: pdmclk_min 500000 pdm_clkmax 4800000 duty_min 40
$cmd was sof-kernel-dump.sh
2020-09-20 21:28:46 UTC [REMOTE_ERROR] Cannot find the sof audio version
2020-09-20 21:28:46 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2020-09-20 21:28:46 UTC [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2020-09-20 21:28:46 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/verify-sof-firmware-load.sh:40
2020-09-20 21:28:46 UTC [REMOTE_INFO] Test Result: FAIL!
```

This issue is randomly reproduced on JSL, EHL, GLK, BDW since ww32 or even earlier:
* GLK on ww39.1, report ID 454
* JSL_RVP_NOCODEC & BDW_WSB_RT286 on ww37.1, report ID 369
* JSL_RVP_HDA in ww35 after we can start stable daily test on this platform, report ID 316
* GLK/EHL in ww32 report ID 207 and 203

2020-07-31 21:35:28 UTC [REMOTE_INFO] Checking SOF Firmware load info in kernel log
2020-07-31 21:35:28 UTC [REMOTE_ERROR] Cannot find the sof audio version
2020-07-31 21:35:28 UTC [REMOTE_INFO] Test Result: FAIL!

(internal issue is 556)

**Comment by mengdonglin** [comment]
This issue can still be reproduced on JSL_RVP_NOCODEC in ww41, test report ID #524 #527. 
https://github.com/thesofproject/sof-test/pull/419 has been merged.

**Comment by marc-hb** [comment]
#419 was not meant to fix this.

**Comment by mengdonglin** [comment]
We plan to use journalctl to fix this issue

**Comment by marc-hb** [comment]
@xiulipan can you confirm this was a clock synchronization issue that made `journalctl` output empty? If confirmed can we close this?

**Comment by marc-hb** [comment]
@xiulipan ping?

**Comment by xiulipan** [comment]
@marc-hb I think after we switch to use journalctl, this issue is not seen for long. Please confirm we can close this issue.

**Comment by marc-hb** [comment]
Agreed, can re-open if seen again.

**Comment by greg-intel** [comment]
Is this the same issue?
https://sof-ci.sh.intel.com/#/result/planresultdetail/9882?model=BDW_WSB_RT286&testcase=verify-sof-firmware-load
(That test run linked to this ticket, so I thought I'd connect back to it.)
