### ISSUE TITLE
add new pause-release  test case for mixer pipeline

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#449]
https://github.com/thesofproject/sof/issues/3522 shows that our current sof-test fails to detect a conceptual bug with the mixer

Changing the pause times with deterministic values (as asked in https://github.com/thesofproject/sof-test/issues/301) would not help, what we really need is to test the state machine transitions once, before going into the random tests.

This means a test such as 

````sh
for stream in all streams
    start stream
    for stream2 in concurrent streams
        start stream2
        pause_push  stream2
        pause_release stream2
        stop stream2
    pause_push stream
    for stream2 in concurrent streams
        start stream2
        pause_push  stream2
        pause_release stream2
        stop stream2
    pause_release stream
    stop stream
    for stream2 in concurrent streams
        start stream2
        pause_push  stream2
        pause_release stream2
        stop stream2
````

We don't need a long time for each action, e..g 500ms would do, so this could be rather quick overall.

**Comment by xiulipan** [comment]
@plbossart I think now we have https://github.com/thesofproject/sof-test/blob/master/test-case/multiple-pause-resume.sh to cover this case. Please confirm can we close this issue
