### ISSUE TITLE
Remove sof-test dependency on topology file, use /proc instead

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/sof-test#471]
From @ranj063 
> @plbossart @aiChaoSONG @marc-hb this PR (#430) is in the right direction. I think we should decouple sof-test from the topology file even when testing with the SOF driver and use the procfs info for the card/pcm info and even for the topology graph using the asoc dapm info. This will also make sure that we dont have assumptions about the default card number. What do you think?

**Comment by marc-hb** [comment]
From @plbossart 
> Agree that if we can use the /proc info then we have all the information needed for tests with PCM devices.
For probes it's actually the only solution since we expose a compressed interface that will never be shown in the topology but will be shown in the card properties (if it's not show it's a bug). The probes are like 'blue wires', they are not set in stone and not shown in the topology.

> Having the topology would only help to show the graph as an information but would not have an functional input into the tests.

**Comment by marc-hb** [comment]
> Agree that if we can use the /proc info then we have all the information needed for tests with PCM devices.

PR #430 has the following code:
```python
for pcm in card_info['pcm']:
                # There are limited pipeline parameters in the proc file system,
                # add some default parameters to make use of sof-test for legacy HDA test
                pcm['fmt'] = 'S16_LE'
                pcm['fmts'] = 'S16_LE S24_LE S32_LE'
                pcm['rate'] = '48000'
                pcm['channel'] = '2'
                pcm['dev'] = 'hw:{},{}'.format(card_id, pcm['id'])
```
@ranj063 , @plbossart  Is this not actually needed for testing?

BTW `Auxiliary devices in SOF break SOFCARD` #466 seems related.

**Comment by aiChaoSONG** [comment]
@marc-hb For SOF test, we have to depend on topology. Because we cannot get the information from proc, eg:
- We can't identify WoV pipeline/Echo Reference pipeline/DSM pipeline from proc, which need special test case for the feature.
- We can't get component parameters from proc, eg: `SOF_TKN_VOLUME_RAMP_STEP_TYPE 
 SOF_TKN_VOLUME_RAMP_STEP_MS`

**Comment by xiulipan** [comment]
> > Agree that if we can use the /proc info then we have all the information needed for tests with PCM devices.
> 
> PR #430 has the following code:
> 
> ```python
> for pcm in card_info['pcm']:
>                 # There are limited pipeline parameters in the proc file system,
>                 # add some default parameters to make use of sof-test for legacy HDA test
>                 pcm['fmt'] = 'S16_LE'
>                 pcm['fmts'] = 'S16_LE S24_LE S32_LE'
>                 pcm['rate'] = '48000'
>                 pcm['channel'] = '2'
>                 pcm['dev'] = 'hw:{},{}'.format(card_id, pcm['id'])
> ```

@marc-hb right, you have found the limitation for the proc info. This is the workaround code to provide a fake PCM capability (hw_params) to the PCMs from proc. In TPLG, we can get those info by parse the binary.
When you try to cat the hw_params info from a PCM in proc, you will only get
```
/proc/asound/card0/pcm0c/sub0$ cat hw_params
closed
```

Another gaps we have with **proc** info is that we could not get the info about the comps in pipeline for the PCM. Some test case is designed for special COMP (eg: MUX, EQ, WOV). So I think we can use **proc** as a fallback, but we could not relay on the proc info for our test.

**Comment by ranj063** [comment]
> Another gaps we have with **proc** info is that we could not get the info about the comps in pipeline for the PCM. Some test case is designed for special COMP (eg: MUX, EQ, WOV). So I think we can use **proc** as a fallback, but we could not relay on the proc info for our test.

@xiulipan what are we missing for these special comps that we read from topology?

**Comment by ranj063** [comment]
> @marc-hb For SOF test, we have to depend on topology. Because we cannot get the information from proc, eg:
> 
> * We can't identify WoV pipeline/Echo Reference pipeline/DSM pipeline from proc, which need special test case for the feature.
@aiChaoSONG wov is always the DMIC16k device. For DSM, the speaker PCM device will have the same name for the feedback pipeline and for echoref, the pipeline is simply called echo. What more info do we need from tplg?

> * We can't get component parameters from proc, eg: `SOF_TKN_VOLUME_RAMP_STEP_TYPE   SOF_TKN_VOLUME_RAMP_STEP_MS`

What do we use these for?

**Comment by ranj063** [comment]
> * We can't get component parameters from proc, eg: `SOF_TKN_VOLUME_RAMP_STEP_TYPE   SOF_TKN_VOLUME_RAMP_STEP_MS`

What do we use these for?

**Comment by aiChaoSONG** [comment]
@ranj063 I think below useful information cannot be extracted from proc, either.
- rate, channel count and supported formats, need to query with alsa API.
- SOF_TKN_VOLUME_RAMP_STEP_MS: this defines the duration of the volume ramp in a PGA, which is useful in volume test
- PCM/pipeline <-> PGA mapping, 

>  wov is always the DMIC16k device
Yes, But the reverse may not be true, right? should we run WoV test on all devices with DMIC16k, even it may not act as WoV pipeline? We do have such device with DMIC16k, but without WoV support.

**Comment by xiulipan** [comment]
@ranj063 @aiChaoSONG I think /proc info only is not enough to get similar info as TPLG parser can do.
We may need to use ALSA API to query the info (eg: aplay --dump-hw-params), we can do some experiment later to see if this would work in most case and get correct info for the test.

If above steps can work, TPLG reader can still be kept for PCM info validation test and some audio quality test that may need detailed configuration value.

**Comment by plbossart** [comment]
@xiulipan even for legacy HDaudio it's much better to query the capabilities instead of hard-coding 48kHz as suggested.

That said you are not going to do a volume test or PCM/pipeline->PGA mapping for legacy HDaudio, so we probably need to move to a mode where the topology is only used when absolutely needed, instead of being the source of all information.

**Comment by xiulipan** [comment]
@plbossart I think I have made some alignment with @ranj063 @aiChaoSONG to have a feature to read /proc or query from ALSA API to get the correct PCM info. But this will take time to make sure the read out info is trustful and won't break SOF FW before we start the test.

reference to get those info by API: 

- https://chromium.googlesource.com/chromiumos/platform/audiotest/+/master/alsa_conformance_test.md
`alsa_conformance_test -P hw:0,0 --dev_info_only`  
https://chromium.googlesource.com/chromiumos/platform/audiotest/+/refs/heads/master/alsa_conformance_test/alsa_conformance_helper.c#169

- aplay --dump-hw-params

- https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html

**Comment by aiChaoSONG** [comment]
some parameter can only be extracted from topology, so a full replacement is impossible, but for platforms use legacy HDA drivers like RKL-S, we can run sof-test on there platforms by reading /proc.  close? @marc-hb

**Comment by marc-hb** [comment]
> so we probably need to move to a mode where the topology is only used when absolutely needed, instead of being the source of all information.

How far from that are we?

**Comment by xiulipan** [comment]
> > so we probably need to move to a mode where the topology is only used when absolutely needed, instead of being the source of all information.
> 
> How far from that are we?

For legacy HDA DUT, we are using /proc but with **FAKED** rate, channel and format info. I do not think using /proc like this can satisfy our test case requirement.

To get fully info, we will need to query the PCM with `--dump-hw-params` which makes test case more complex.

**Comment by marc-hb** [comment]
I just made `sof-get-default-tplg.sh` compatible with the new `cavs` / IPC4 topologies:
-  https://github.com/thesofproject/sof-test/pull/854

It works by scanning the kernel logs so it does not work until the driver has been loaded.

**Comment by marc-hb** [comment]
@plbossart  reported an interesting side effect of this in https://github.com/thesofproject/linux/pull/3645#issuecomment-1137902429

When everything goes well, the list of pipelines comes from the $TPLG file. This file obviously does not include any USB device.

When the firmware crashes or does not load for some reason, `sof-test/case-lib/pipeline.sh#func_pipeline_export()` assumes it's running in "legacy HDA" mode and falls back on `sof-dump-status.py -e "$filter_str"` which _does_ read (fewer data fields?) from `/proc`. Unlike the $TPLG file, `/proc` does include USB devices. Confusion ensues.

There's probably a bug somewhere.

**Comment by marc-hb** [comment]
Quoting one of the commit messages in (long)
- #430 

> This patch adds is_sof_used function to check (whether) we are running test on SOF platform or legacy HDA platform.

**Comment by marc-hb** [comment]
From experience, automated fallbacks are a generous source of "green failures".

In https://github.com/thesofproject/linux/pull/3645#issuecomment-1137902429, this automated fallback certainly tries to hide an SOF crash.

Maybe sof-test should by default test SOF device and nothing else.

If someone wants to test non-SOF devices, they can but they should have to ask explicitly.

Testing is about finding and reporting as many problems as possible. Fallbacks do the exact opposite.

**Comment by aiChaoSONG** [comment]
@plbossart @marc-hb We do test legacy-hda on RKL device, check report 12889. But looks no one has ever checked it.

**Comment by plbossart** [comment]
Agree, if people want to test on HDaudio or USB or whatever, they should use the card name explicitly. That's a great feature to allow sof-test to be used in a generic way.

Fallback is evil in this case, we end-up testing the wrong card if by accident the one we want was not registered. Big conceptual fail IMHO. Typical issues will be using the NVidia HDMI card or USB audio, not of which are intended in our CI tests.

**Comment by marc-hb** [comment]
> Agree, if people want to test on HDaudio or USB or whatever, they should use the card name explicitly. That's a great feature to allow sof-test to be used in a generic way.

I think it would be best but it would be some coding effort. In the meantime here's a quickfix from @aiChaoSONG that turns off the fallback by default:
- https://github.com/thesofproject/sof-test/pull/914

**Comment by marc-hb** [comment]
New fw_profile worth noting:
- https://github.com/thesofproject/sof-test/pull/1167

**Comment by marc-hb** [comment]
Maybe reading `/proc/` is better in some cases, but sof-test will always need information from topologies. Recent examples:
- https://github.com/thesofproject/sof-test/commit/82b4831f8d2d216e0233347a5a3b93dbaad20931
- https://github.com/thesofproject/sof-test/issues/1185

So, closing.
