### ISSUE TITLE
kmod-load-unload fails to recognise an underlying kernel error

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#473]
As described in https://github.com/thesofproject/linux/issues/2535 a kmod-load-unload test failed with "dsp is not suspended after 15s" and it failed to identify the underlying kernel error.

**Comment by aiChaoSONG** [comment]
@lyakh before starting test, we will wait DSP to suspend, if you see the `dsp is not suspended after 15s`, that means we have issues.
Previous error may cause the DSP keeps alive.

**Comment by lyakh** [comment]
@aiChaoSONG exactly, an IPC timeout causes
> sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
> sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context

I understand that, but I think, that that should be identified and printed by test scripts. Usually our test scripts do grep dmesg for error messages, so it would be trivial for them and more useful for developers to see the actual error instead of just a timeout entering suspend

**Comment by marc-hb** [comment]
@lyakh  can you still reproduce this? There's been a number of changes in sof-test since you filed it.
Also appreciate if you can provide detailed reproduction steps.

Is the problem the lack of kernel log check? Just to make sure we understand each other.

**Comment by mengdonglin** [comment]
Close as no response for a long time.
