### ISSUE TITLE
CI result pages: make individual results linkable

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof-test#477]
In a CI result page like:
https://sof-ci.01.org/linuxpr/PR2524/build4796/devicetest/

Each PASS/FAILURE result now opens a pop-up. This is convenient when browsing the results, but when I need to communicate that one test failed on a specific platform, I don't have a link to copy that would take the reader directly to the failing test+platform. Instead I'll point to the https://sof-ci.01.org/linuxpr/PR2524/build4796/devicetest/ result page and have to type in that there's one failure on TGL RVP, or something to that effect.

Especially when merging, I'd like to be able to point to a specific failure. E.g. test run "link-to-failed-case" failed on this PR, but I've checked it and it's not related to this PR and I'm going to merge the PR still. Now I have to often end up just pointing to the whole results page and explaining that something failed, but I did check it, I think it's ok and will merge.

I know there are pros and cons, but I'm starting to lean towards preferring normal links versus popups.

**Comment by kv2019i** [comment]
Additional problem: At least with Chrome, I can't copy'n'paste the DUT name from the table. So I end up manually copying the failing DUT type from the results to my mail/comment.

**Comment by aiChaoSONG** [comment]
Xiuli suggest to use anchor to do this.

**Comment by marc-hb** [comment]
@kv2019i does the new "Copy Link" button solve this, happy to close?

https://sof-ci.01.org/softestpr/PR503/build373/devicetest/?model=BYT_MB_NOCODEC&testcase=check-alsabat-headset-playback

**Comment by plbossart** [comment]
What exactly does this 'Copy Link' do? I paste it in another tab and can't get any useful info. The only thing that gets downloaded is wav files that are not related to the test I was looking for.

**Comment by marc-hb** [comment]
> The only thing that gets downloaded is wav files that are not related to the test I was looking for.

I never downloaded these and I don't link this automatic download either but I hope these files _are_ related to the corresponding test! What happens after you cancel the download?

Here's another example without any automatic download https://sof-ci.01.org/softestpr/PR503/build373/devicetest/?model=ICL_RVP_HDA&testcase=verify-sof-firmware-load

**Comment by aiChaoSONG** [comment]
we have link for each test case on a model, can we close? @kv2019i

**Comment by marc-hb** [comment]
I (and many others) hve been using that feature a lot, it's extremely useful. So I confirm this is done, closing. @kv2019i  please re-open if you "prefer popup to normal links" or if anything else was missed.

**Comment by marc-hb** [comment]
> Each PASS/FAILURE result now opens a pop-up. 

The technical term is "modal dialog" or (on the web) "modal overlay".

> I know there are pros and cons, but I'm starting to lean towards preferring normal links versus popups.

The "Copy Link" button implemented here helped but it solved only one problem. I think a regular page would be much better for other reasons too. I created a "poll" to collect opinions, please vote up or down #816
