### ISSUE TITLE
Highlight row when mouse hovers over it on device test page

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof-test#491]
With the device table getting bigger by the day, it is getting a bit tricky to match the row item on the last colum with the first column which has the test name. Highlighting the row when the mouse moves hovers over it would make it easier to see if the user is clicking the right link.

**Comment by aiChaoSONG** [comment]
this is done by xiuli, check https://sof-ci.01.org/softestpr/PR503/build373/devicetest/

**Comment by marc-hb** [comment]
@ranj063  ok to close?

**Comment by ranj063** [comment]
brilliant. Thank you for the quick turnaround!
