### ISSUE TITLE
[RFC] NA or Fail if no pipeline is detected?

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#504]
should we fail the case or make it NA if no pipeline is detected from topology or /proc?

Currently, some test cases don't check pipeline count, we will have a false PASS if no pipeline is present.

**Comment by marc-hb** [comment]
I think so.

@ranj063 , @plbossart , @fredoh9 , @xiulipan , @kv2019i 
Can anyone think of any sof-test where zero pipeline is a valid configuration? Then we could probably offer this test(s) the ability to ignore the "zero pipeline failure" but the default should IMHO to fail.

**Comment by aiChaoSONG** [comment]
close for patch merged.
