### ISSUE TITLE
Clean some info/dbg level ignore str

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#548]
Previously, we add a lot of info/dbg level ignore str, and now we are switching to journalctl, and only error level message is collected now. let's clean up old ignore string.

**Comment by marc-hb** [comment]
Discussed in the bug scrub, agreed to have regular cleanups like bug scrubs.

To cleanup: look at the URL, send a PR without that line, check recent logs on the corresponding platform.
