### ISSUE TITLE
Filter out irrelevant asix error.

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof-test#565]
CI detected this error when testing “check-suspend-resume-50” on TGLH platform.
```
kernel: [ 7321.220312] asix 3-12.1:1.0 enx000ec668ad2a: Failed to read reg index 0x0000: -113
kernel: [ 7321.220314] asix 3-12.1:1.0 enx000ec668ad2a: Failed to write reg index 0x0000: -113
kernel: [ 7321.220315] asix 3-12.1:1.0 enx000ec668ad2a: Failed to enable software MII access
```

1371?model=TGLH_RVP_HDA&testcase=check-suspend-resume-50

**Comment by keqiaozhang** [comment]
Looks like this a network hardware issue, asix_bind return error when hw reset fails. I have switched the network to another network port on motherboard. if this doesn't help, I will try to use the USB network adapter.

**Comment by keqiaozhang** [comment]
CI detected the similar asix USB Ethernet issue on CML Chrome device when testing suspend/resume.  
```
kernel: [ 7974.604354] ax88179_178a 2-2.3:1.0 enx000ec66a7f60: Failed to read reg index 0x0002: -19
kernel: [ 7974.604367] ax88179_178a 2-2.3:1.0 enx000ec66a7f60: Failed to write reg index 0x0002: -19
kernel: [ 7974.619850] ax88179_178a 2-2.3:1.0 enx000ec66a7f60 (unregistered): Failed to write reg index 0x0002: -19
kernel: [ 7974.619870] ax88179_178a 2-2.3:1.0 enx000ec66a7f60 (unregistered): Failed to write reg index 0x0001: -19
kernel: [ 7974.619881] ax88179_178a 2-2.3:1.0 enx000ec66a7f60 (unregistered): Failed to write reg index 0x0002: -19
kernel: [ 7974.622730] xhci_hcd 0000:00:14.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
```
https://sof-ci.sh.intel.com/#/result/planresultdetail/1547?model=CML_HEL_RT5682&testcase=check-suspend-resume-with-playback-25

**Comment by marc-hb** [comment]
> I have switched the network to another network port on motherboard.

@keqiaozhang can you confirm `asix 3-12.1:1.0 enx000ec668ad2a` is on the motherboard? Are the network interfaces on the motherboard all USB? `lsusb -tv` might help.

I see other USB errors, maybe a generic USB issue.

**Comment by keqiaozhang** [comment]
> > I have switched the network to another network port on motherboard.
> 
> @keqiaozhang can you confirm `asix 3-12.1:1.0 enx000ec668ad2a` is on the motherboard? Are the network interfaces on the motherboard all USB? `lsusb -tv` might help.
> 
> I see other USB errors, maybe a generic USB issue.

CI detected this network issue on three different platforms and we used the USB lan adaptor on these DUTs, I think it's a generic USB issue.

**Comment by marc-hb** [comment]
I'm still confused sorry.
- So all these USB errors are with USB adapters/dongles, correct? Never with a "network port on the motherboard"?
- If it's always with the same driver then it does not point at a generic USB issue. Can you test with a different USB adapter, one with a different driver?

**Comment by keqiaozhang** [comment]
> I'm still confused sorry.
> 
> * So all these USB errors are with USB adapters/dongles, correct? Never with a "network port on the motherboard"?
> * If it's always with the same driver then it does not point at a generic USB issue. Can you test with a different USB adapter, one with a different driver?

So far, we observed this issue on 2 platforms: ICL_RVP_HDA and TGLH_RVP_HDA, but not sure if those devices are using the same USB adapter because the failed DUT of ICL_RVP_HDA was set up by Fred in JF lab. I will try with another USB adapter on TGLH_RVP_HDA in SH.

**Comment by keqiaozhang** [comment]
I setup a new TGL-H Beta desktop with a new type of USB adapter, daily test got "ALL PASS", no asix related errors. I will replace all our TGL-H Alpha desktops to the Beta one in our CI and continue to track this issue in CI test.  
@fredoh9 , this issue happens when testing suspend/resume related cases, so could you please help to check the USB adapter on ICL_RVP_HDA？

**Comment by xiulipan** [comment]
@keqiaozhang Could you help to check what driver is used for our USB adapters? We need to check if it is possible to not use asix device or we still need to filter the erros.

**Comment by keqiaozhang** [comment]
CI observed another type of asix error on TGLH_0A5E_SDW. Daily test ID:2491
```
[ 7584.440914] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable software MII access
[ 7584.442046] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable software MII access
[ 7584.443163] kernel: asix 3-3.1:1.0 enx000ec65356e1: Failed to enable software MII access
```

**Comment by fredoh9** [comment]
@keqiaozhang do we still asix error not covered? can you confirm and close this?

**Comment by fredoh9** [comment]
Found new error on TGLH_RVP_HDA
```
===========================>>
[  117.616999] kernel: asix 3-4:1.0 enx8cae4cfe1882: asix_rx_fixup() Bad Header Length 0x4b203a6e, offset 4
<<===========================
```

**Comment by fredoh9** [comment]
Sorry, this isn't new.
`3-3.1:1.0` was handled but not `3-4:1.0`. Will update the filter.

**Comment by mengdonglin** [comment]
Fix merged and so close it.
