### ISSUE TITLE
[RFC] Rename variables for defining script's options

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#572]
We have for variables named `OPT_DESC_lst` `OPT_OPT_lst` `OPT_PARM_lst` `OPT_VALUE_lst` used for defining script's options. And I just think they are not very to the point, so I decide to rename them to:
`OPT_NAME`, `OPT_ARG_COUNT`, `OPT_ARG_VAL` and `OPT_DESC`

Currently, our option definition code looks like this:
```
OPT_OPT_lst['t']='tplg'     OPT_DESC_lst['t']='tplg file, default value is env TPLG: $''TPLG'
OPT_PARM_lst['t']=1         OPT_VALUE_lst['t']="$TPLG"
```
Two sentences are written in one line, that's not clean and tidy, either.
I want to first rename the variable names, and rearrange the code for script options. After this, we should be less painful.
I'd like to hear from you,  @xiulipan @marc-hb  @fredoh9 @keqiaozhang

**Comment by marc-hb** [comment]
I agree the names are confusing, I have to check the comments in `opt.sh` every time (copied below for convenience).

`OPT_NAME` LGTM and keeping `OPT_DESC` too.

`OPT_ARG_COUNT` can only be 0 or 1, it's basically a boolean so how about `OPT_HAS_ARG`?

For `OPT_ARG_VAL` I prefer `OPT_VAL` because it's used  even when there is no ARG (as another boolean)


```shell
# option setup && parse function
func_opt_parse_option()
{
    # OPT_OPT_lst     (long) option name
    # OPT_DESC_lst    short sentence describing the option
    # OPT_PARM_lst    0 or 1: number of argument required
    # OPT_VALUE_lst   default value overwritten by command line
    #                 input if any. Set to 0 or 1 when PARM=0

    # for example
    # OPT_OPT_lst['r']='remote'
    # OPT_DESC_lst['r']='Run for the remote machine'
    # OPT_PARM_lst['r']=1
    # OPT_VALUE_lst['r']='' ## if PARM=1, must be set, if PARM=0, can ignore

    # h & help is default option, so don't need to add into option list
    OPT_OPT_lst['h']='help'
    OPT_DESC_lst['h']='this message'
    OPT_PARM_lst['h']=0
    OPT_VALUE_lst['h']=0

```

**Comment by aiChaoSONG** [comment]
A PR for `OPT_OPT_lst` and `OPT_DESC_lst` renaming is submitted: https://github.com/thesofproject/sof-test/pull/573
@marc-hb I totally agree with `OPT_HAS_ARG` and `OPT_ARG_VAL`, let's wait for some more inputs.
@xiulipan Please give your opinion or review my PR.

**Comment by xiulipan** [comment]
@marc-hb @aiChaoSONG `OPT_HAS_ARG` should be a better name
@aiChaoSONG please help to create with a new PR.

**Comment by aiChaoSONG** [comment]
@xiulipan Let's don't so hurry to close it.
@marc-hb  If we use `OPT_HAS_ARG`, it's better to use its brother `OPT_ARG` instead of `OPT_VAL`. 
> For OPT_ARG_VAL I prefer OPT_VAL because it's used even when there is no ARG (as another boolean)

I think this is also what we should fix,  if the option has an arg, the arg should be specified with `OPT_ARG`, if there is no arg for the option, just don't specify it, there is no reason to have a redundant boolean.

A PR renames OPT_PARM_lst to OPT_HAS_ARG, OPT_VALUE_lst to OPT_ARG is here. https://github.com/thesofproject/sof-test/pull/574

**Comment by xiulipan** [comment]
@aiChaoSONG I did not realize the merge automatically close this issue.

I checked #574, we also need to take care of the inline comments if we do those changes.

**Comment by marc-hb** [comment]
> if there is no arg for the option, just don't specify it, there is no reason to have a redundant boolean.

Redundant with what else? Where do you know whether the option was passed?
