### ISSUE TITLE
Filter out irrelevant iwlwifi error

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#578]
```
[ 6572.558792] kernel: iwlwifi 0000:00:14.3: No beacon heard and the time event is over already...
```

**Comment by lyakh** [comment]
should be fixed by https://github.com/thesofproject/sof-test/pull/581

**Comment by marc-hb** [comment]
I think we should ignore everything from `iwlwifi` (or even better: blacklist it). Hopefully it's not going to crash the system.

However #581 also ignores errors from wired network adapters.

**Comment by xiulipan** [comment]
Close via #601 merged.
