### ISSUE TITLE
filter out USB related error logs

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#582]
seen on https://sof-ci.01.org/softestpr/PR579/build549/devicetest/?model=CML_HEL_RT5682&testcase=check-kmod-load-unload
```
[  894.731264] kernel: usb 1-2.4: 1:1: cannot set freq 48000 to ep 0x1
[  894.731690] kernel: xhci_hcd 0000:00:14.0: ERROR: unexpected command completion code 0x13.
[  894.732062] kernel: usb 1-2.4: 2:1: cannot set freq 48000 to ep 0x82
[  894.732292] kernel: xhci_hcd 0000:00:14.0: ERROR: unexpected command completion code 0x13.
[  894.732701] kernel: usb 1-2.4: 13:0: cannot get min/max values for control 2 (id 13)
[  894.732826] kernel: usb 1-2.4: 9:0: cannot get min/max values for control 2 (id 9)
[  894.732899] kernel: usb 1-2.4: 10:0: cannot get min/max values for control 2 (id 10)
```

**Comment by marc-hb** [comment]
>  kernel: usb 1-2.4: 2:1: cannot set freq 48000 to ep 0x82

This really looks like an audio issue.

**Comment by xiulipan** [comment]
Please check https://bugzilla.redhat.com/show_bug.cgi?id=1240798
looks like a audio USB card issue.

**Comment by keqiaozhang** [comment]
```kernel: usb 1-2.4: 2:1: cannot set freq 48000 to ep 0x82```
This line of error reminds me of a recent change in our sof-test, I removed the "plughw" in alsabat test and specified the freq to 48000.  
@fredoh9 , could you help to check if the USB sound card supports 48K format? A lot of USB errors happen on CML_HEL_RT5682 and most of the devices are in JF lab.  BTW, we are using the UGREEN sound cards in SH.
![Capture](https://user-images.githubusercontent.com/22468760/105934148-96ff5000-608a-11eb-92cb-0b7323f46274.PNG)

**Comment by keqiaozhang** [comment]
Found a new type of USB adaptor error log on CML_HEL_RT5682
Daily report ID:1995
```
[ 8320.406890] kernel: r8152 2-1.4:1.0 enx00e04c733c81: can't resubmit intr, status -1
```

**Comment by keqiaozhang** [comment]
we haven't seen this issue in CI for a long time.  Let's close this issue and reopen it if needed.
