### ISSUE TITLE
Allow user to skip display audio pipelines in test

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof-test#585]
We need the test cases can accept a config parameter to skip all display audio PCMs and only test other PCMs.

This can help CI to support very new platforms. For these platforms, i915 display driver support is not ready in upstream mainline kernel, so all test on display pipelines will fail and block test on other pipelines.  We hope the test cases can be configured and allow  us to test non-display pipelines only w/o modifying the topology files.

**Comment by aiChaoSONG** [comment]
A dev topology is here: https://github.com/thesofproject/sof/pull/3779

**Comment by mengdonglin** [comment]
@kv2019i will take over the testing topology https://github.com/thesofproject/sof/pull/3779

**Comment by aiChaoSONG** [comment]
https://github.com/thesofproject/sof-test/pull/644 is merged, and issue fixed
