### ISSUE TITLE
[BUG] filter out USB adaptor r8152 error 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof-test#603]
**Describe the bug**
This is a new type of USB adaptor error on CML_HEL_RT5682 when testing suspend/resume case.
Daily report ID: 1995
Error:
```
sh-cml-hel-rt5682-05 kernel: [ 8320.406890] r8152 2-1.4:1.0 enx00e04c733c81: can't resubmit intr, status -1

```

**Comment by marc-hb** [comment]
Let's not use network adapters that output errors.

**Comment by fredoh9** [comment]
I will replace with different adaptor known to work fine.

**Comment by fredoh9** [comment]
Found r8152 error in daily test id 2305. DUT is `sh-tglu-volt-sdw-03`.

`[ 1302.910119] kernel: r8152 3-4.1:1.0 enx9405bb16746a: can't resubmit intr, status -1`

**Comment by fredoh9** [comment]
For CML_HEL_RT5682, I don't see usb error any more after replacing the USB adaptor.

**Comment by keqiaozhang** [comment]
No reproductions in CI. let's close this bug.
