### ISSUE TITLE
[FEATURE] "check-logs" dummy test to merely check boot time errors

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/sof-test#605]
**Is your feature request related to a problem? Please describe.**
Kernel errors at boot time are either not reported properly or not detected at all and stay unnoticed. This is a well known issue and especially bad considering we load audio drivers at boot time right now.
See recent example at https://sof-ci.01.org/sofpr/PR3790/build8042/devicetest/?model=TGLU_RVP_SDW&testcase=verify-sof-firmware-load

**Describe the solution you'd like**
A dummy test named "check-logs" or similar that does nothing except use the same framework as other tests and scanning logs for errors exactly like all other tests do. By always running it as the very first test before any other test had a chance to set a KERNEL_CHECKPOINT (= test start time to ignore errors from previous tests), this test should automatically check the logs all the way from the boot time.

**Describe alternatives you've considered**
In the future we may want to be smarter and for instance check boot logs after each reboot to catch non-deterministic boot errors too. However reboot is dynamic depending on test results so this will be much more work. This simple test should catch all deterministic boot time errors and maybe some non-deterministic errors too for a very small effort.

See related internal issue 466

**Comment by marc-hb** [comment]
For local development the `fake_kern_error()` function should be useful.

**Comment by marc-hb** [comment]
@aiChaoSONG  is this running now?

**Comment by aiChaoSONG** [comment]
@marc-hb  Yes, both in daily and PR test, close?

**Comment by marc-hb** [comment]
Yes,  thank you @aiChaoSONG for knocking yet another one down!
