### ISSUE TITLE
[BUG] more USB errors to be filtered out

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#610]
I am starting to lean towards a blanket ignore of all USB issues:

https://sof-ci.01.org/linuxpr/PR2739/build5261/devicetest/?model=CML_HEL_RT5682&testcase=check-kmod-load-unload-after-playback

````
===========================>>
[  974.089782] kernel: usb 1-2-port4: Cannot enable. Maybe the USB cable is bad?
[  975.049792] kernel: usb 1-2-port4: Cannot enable. Maybe the USB cable is bad?
[  976.018798] kernel: usb 1-2-port4: Cannot enable. Maybe the USB cable is bad?
<<===========================
````

**Comment by keqiaozhang** [comment]
@fredoh9 has replaced the USB hub with a new model and this error has disappeared in CI.
