### ISSUE TITLE
[BUG] sof-kernel-log-check: filter out NVME log.

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#616]
Need to filter out NVME issue:

https://sof-ci.sh.intel.com/#/result/planresultdetail/2190?model=CML_RVP_SDW&testcase=check-suspend-resume-with-playback-25

[ 6846.214748] kernel: nvme nvme0: Device shutdown incomplete; abort shutdown

**Comment by marc-hb** [comment]
This one apparently means the storage wasn't given power for long enough to shut down correctly (Flash Translation Layer requires complex firmware). Was this following a crash?

@fredoh9 I vaguely remember you dealt with some NVMe storage corruption some time back? I couldn't find any trace of that unfortunately.

**Comment by XiaoyunWu6666** [comment]
synced with @keqiaozhang  that this is with very low frequency so close it temporarily
Will monitor whether it re-appeared in CI tests later

**Comment by marc-hb** [comment]
Re-appeared, spotted by @plbossart : https://sof-ci.01.org/linuxpr/PR3785/build446/devicetest/?model=TGLU_UP_HDA&testcase=check-suspend-resume-with-playback-5

**Comment by marc-hb** [comment]
Below is the corresponding code in `drivers/nvme/host/core.c`. I'm guessing this is harmless as long as we don't power-cycle the system (then it could probably lead to some data corruption).

As long as its rare let's ignore it. If it becomes frequent then we should try to change the hard drive. I don't think we should filter it out in any case, other storage reliability issues just cost @keqiaozhang and @fredoh9 months of work (see https://github.com/thesofproject/linux/issues/3387 and friends)

```C
int nvme_shutdown_ctrl(struct nvme_ctrl *ctrl)
{
        unsigned long timeout = jiffies + (ctrl->shutdown_timeout * HZ);

       ...

        while ((ret = ctrl->ops->reg_read32(ctrl, NVME_REG_CSTS, &csts)) == 0) {
                if ((csts & NVME_CSTS_SHST_MASK) == NVME_CSTS_SHST_CMPLT)
                        break;

                msleep(100);
                if (fatal_signal_pending(current))
                        return -EINTR;
                if (time_after(jiffies, timeout)) {
                        dev_err(ctrl->device,
                                "Device shutdown incomplete; abort shutdown\n");
                        return -ENODEV;
                }
        }

        return ret;
}

```

**Comment by marc-hb** [comment]
Just found by chance that this recently happened another time on the same `sh-tglu-up-hda-02` device!

https://sof-ci.01.org/sofpr/PR5959/build785/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=check-suspend-resume-with-playback-5

Let's keep a close eye on on `sh-tglu-up-hda-02` and change its drive if it gets worse.

**Comment by marc-hb** [comment]
Not reported for a long time, closing. Re-open if seen again.
