### ISSUE TITLE
[FEATURE] sof-test needs to support Fedora 34

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#633]
With the transition in Fedora34 from PulseAudio to Pipewire, some of our scripts dealing with PulseAudio need to be updated.

**Comment by lgirdwood** [comment]
@perexg @jwrdegoede fyi

**Comment by perexg** [comment]
Adding Wim to the chain. @wtay

Could you link us to scripts which should be checked / modified?

**Comment by lgirdwood** [comment]
We have a lot of test scripts here https://github.com/thesofproject/sof-test/tree/master/test-case and IIIUC they all use the ALSA APIs (i.e. none use any PA APIs) so my expectation is that these _should_ work (or require minimal configuration changes).

I think the largest task is probably to integrate the Jenkins based audio test infrastructure we have to additionally support RPM pagkages. Today, Debian based tooling is used to update kernels, modules and tooling on each DUT and we need to make sure we can support RPM here too on F34 and beyond.

@kv2019i @aiChaoSONG @marc-hb  any further comments here ?

**Comment by marc-hb** [comment]
Agreed: 95% of sof-test  should just work on Fedora (please report bugs and/or submit fixes) whereas the Debian packaging of the kernel and ALSA packages is obviously not going to work.

**Comment by plbossart** [comment]
Installing dependencies is straightforward:
````bash
dnf install expect python3-graphviz python3-numpy python3-scipy
````

the rest if less clear:

````
Checking group memberships:		Warning
Solution:

	Missing permission to run command as sudo

		Please use the following command to add current user to the group sudo:

	 sudo usermod --append --groups sudo 
````

why is this needed?

````
	Missing /var/log/kern.log file, which is where we'll catch the kernel log

		Please create the link of your distribution kernel log file at /var/log/kern.log
````

I thought we are now using journalctl? What is this dependency, is it still needed?

**Comment by plbossart** [comment]
````
cut: /var/log/kern.log: No such file or directory
2021-03-29 14:20:32 UTC Sub-Test: [INFO] Test Result: PASS!
````

fantastic.

**Comment by marc-hb** [comment]
There are many commands in `sof-test` that need `sudo`, starting with inserting and removing modules.

> I thought we are now using journalctl? What is this dependency, is it still needed?

It's unfortunately not complete, see internal issue 477 and others. 

> cut: /var/log/kern.log: No such file or directory  [INFO] Test Result: PASS!

#312 should help, it has been implemented on some tests but not others. Does every test "PASS" like this?

The good news is: these are not new issues and not specific to Fedora. The bad news is: all this is down to prioritization. When everything is urgent, nothing is.

**Comment by aiChaoSONG** [comment]
@plbossart check this onging PR, it totally removes /var/log/kern.log, and use journalctl.

> cut: /var/log/kern.log: No such file or directory

Unfortunately, only Ubuntu use this file

**Comment by marc-hb** [comment]
I guess @aiChaoSONG is referring to #639

**Comment by mengdonglin** [comment]
PR #639 was separated to two other PRs #643, #649 that were merged. So sof-test is ready.  The remaining work is remove usage of sudo group but to use audio group for all OSes.  Close this issue.
