### ISSUE TITLE
[Enhancement][log] log collection with journalctl

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#638]
We are still using /var/log/kern.log for log collection, this file is not exist on ChromeOS and Fedora, which makes sof-test not flexible. Replace current log collection with journalctl.

Issue migrate from gitlab: 
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/466
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/477
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/500

**Comment by mengdonglin** [comment]
Duplicate of #466 and #477. Close this.
