### ISSUE TITLE
[FEATURE] need to allow for /lib/firmware/updates/ for firmware path

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#667]
**Is your feature request related to a problem? Please describe.**

sof-test currently hard-codes the firmware path

````
config.sh:10:TPLG_ROOT=${TPLG_ROOT:-/lib/firmware/intel/sof-tplg}
lib.sh:97:            ldcFile=/lib/firmware/intel/sof/sof-"$platf".ldc
````

we want to avoid installing the firmware+topology in the baseline path and use /lib/firmware/updates/ as a preferred path.

**Describe the solution you'd like**

make sure sof-test tries /lib/firmware/updates/ first and then uses /lib/firmware/

**Describe alternatives you've considered**

udev rules -> difficult to manage

https://www.kernel.org/doc/html/latest/driver-api/firmware/fw_search_path.html

**Comment by marc-hb** [comment]
wontfix
