### ISSUE TITLE
[APL] APL_UP2_NOCODEC TIMEOUT when suspend-resume 

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof-test#717]
**Describe the bug**
According to our inner daily tests , APL_UP2_NOCODEC TIMEOUT when suspend-resume quite often (without too much meaningful error/warning logs) .
eg inner daily  4849  model=APL_UP2_NOCODEC  testcase=check-suspend-resume-50
[console log]
```shell
2021-06-24 23:33:43 UTC [REMOTE_INFO] ===== Round(33/50) =====
2021-06-24 23:33:43 UTC [REMOTE_COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Thu Jun 24 23:33:49 2021
2021-06-24 23:33:51 UTC [REMOTE_COMMAND] sleep for 5
2021-06-24 23:33:56 UTC [REMOTE_INFO] Check for the kernel log status
declare -- cmd="journalctl_cmd --since=@1624577618"
2021-06-24 23:33:56 UTC [REMOTE_INFO] Check for the wakeup_count
2021-06-24 23:33:56 UTC [REMOTE_INFO] ===== Round(34/50) =====
2021-06-24 23:33:56 UTC [REMOTE_COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Thu Jun 24 23:34:02 2021
```

TCR shows that all TIMEOUT happen on jf DUTs , no TIMEOUT happen on sh APL_UP2_NOCODEC DUTs.
(You can use filters shown as following)
![image](https://user-images.githubusercontent.com/79959904/123362648-97e9ce80-d5a3-11eb-9373-955ffb0f6e0a.png)

**Reproduction**
TPLG=sof-apl-nocodec.tplg ~/sof-test/test-case/check-suspend-resume.sh -l 50

**Comment by XiaoyunWu6666** [comment]
thanks @fredoh9  for refining the TIMEOUT value for jf APL_UP2_NOCODEC DUTs. (they have longer network delay so bigger TIMEOUT value should be used!)
Let's close it if following inner daily tests work well

**Comment by plbossart** [comment]
@XiaoyunWu6666 this doesn't seem like a current issue?

**Comment by marc-hb** [comment]
rtcwake timeout in daily 14218?model=APL_UP2_HDA_ZEPHYR&testcase=check-suspend-resume-without-audio-20 Start Time: 2022-07-25 21:29:47 UTC

**Comment by marc-hb** [comment]
Not seen for a long time - at least not more frequently than on other platforms.
