### ISSUE TITLE
[FEATURE] Before running check-alsabat, set all gains to 0dB and enable all Switches

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#721]
**Is your feature request related to a problem? Please describe.**
The sof-test scripts don't set mixer values for the SOF firmware. This can lead to failed test reports when the issue is really a mixer setup.

**Describe the solution you'd like**
Save the mixer values before running alsa-bat
Set all 'PGA' gains to 0dB
Set all Switches on
Run alsa-bat
Restore prior mixer values.

**Describe alternatives you've considered**
none

**Additional context**
See Intel daily test 4904, capture is all zeroes. Not manually reproducible since values are different on all platforms.

**Comment by marc-hb** [comment]
I think that's done now since commit 31f55038b585 and more, please re-open if not.
