### ISSUE TITLE
[BUG]alsa settings for NOCODEC platforms don't fit APL_UP2_NOCODEC_ZEPHYR and TGLH_RVP_NOCODEC_ZEPHYR 

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof-test#745]
APL_UP2_NOCODEC_ZEPHYR and TGLH_RVP_NOCODEC_ZEPHYR failed when check-alsabat-headset-playback becasue of alsa setting (volume too high)
I checked other NOCODEC platforms ,actually CAVS_NOCODEC.sh work good for other NOCODEC platforms except for these two NOCODEC_ZEPHYR platforms.
Should we provide extra alsa settings for them? Or maybe some other walkarounds are available.

**Comment by kv2019i** [comment]
@XiaoyunWu6666 Let's not change anything yet. Changing to Zephyr as OS should not affect the behaviour of pipelines this way. E.g. if these settings are good for APL_UP2_NOCODEC, then the same should work for APL_UP2_NOCODEC_ZEPHYR. FYI to @lyakh and @marc-hb . This is really odd, how could the OS affect volume levels? Ideas are welcome.

**Comment by kv2019i** [comment]
@singalsu Any ideas? One thing that popped to my mind is that we are compiling the Zephyr FW images with gcc now? Maybe we have some regression in gcc built DSP components causing audio to go haywire...?

**Comment by marc-hb** [comment]
Wild guess: do ALSA settings work with Zephyr?

**Comment by plbossart** [comment]
I ssd'ed into sh-apl-up2-nocodec-zephyr-01.sh.intel.com and see this:

PGA1.0 1 Master [dB gain: -40.00, -40.00] 
PGA2.0 2 Master [dB gain: 30.00, 30.00]    
PGA4.0 4 Master [dB gain: 30.00, 30.00]   
PGA6.0 6 Master [dB gain: 30.00, 30.00]

@fredoh9 do we apply the CAVS_NOCODEC.sh script for the Zephyr nocodec targets? Clearly the mixer values are wrong.

**Comment by fredoh9** [comment]
missing for Zephyr nocodec platforms. Will submit the PRs shortly.
