### ISSUE TITLE
[FEATURE] Add a new test for suspend/resume during pause

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof-test#756]
**Is your feature request related to a problem? Please describe.**
This is a gap in our validation. We do not check for issues with suspend/resume when some streams are paused.

**Describe the solution you'd like**
Add a new test for suspend/resume with audio making sure that the open audio device is paused before suspending

**Comment by mengdonglin** [comment]
Here is the upstream test scripts:
https://github.com/thesofproject/sof-test/blob/main/test-case/check-pause-release-suspend-resume.sh

We need to enable this case in CI PR and daily testing. So use internal CI issue number 84 for further tracking.
