### ISSUE TITLE
[BUG] filter out DRM 'Fault errors on pipe A/B'

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#757]
https://sof-ci.sh.intel.com/#/result/planresultdetail/6130?model=CML_RVP_NOCODEC&testcase=verify-kernel-boot-log

[    3.092634] kernel: i915 0000:00:02.0: [drm] *ERROR* Fault errors on pipe B: 0x00000080
[    3.092655] kernel: i915 0000:00:02.0: [drm] *ERROR* Fault errors on pipe B: 0x00000080
[    3.094401] kernel: i915 0000:00:02.0: [drm] *ERROR* Fault errors on pipe A: 0x00000080
[    3.094425] kernel: i915 0000:00:02.0: [drm] *ERROR* Fault errors on pipe A: 0x00000080

**Comment by mengdonglin** [comment]
@fredoh9 Can you help fix this issue?

**Comment by marc-hb** [comment]
I haven't seen this error for a long time, please re-open if observed more recently.
