### ISSUE TITLE
[bugs][tools]sof-dump-status do not full support BYT/CHT/BDW

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#83]
The sof-dump-status.py is not finding the right DSP device for the BYT, CHT and BDW.
Need to use ACPI device for those platforms.

**Comment by Bin-QA** [comment]
check with source code:  [sof-acpi-dev.c](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/sof-acpi-dev.c#L194)

Catch the keyword, how to deal with the PCI information for 'BYT', 'CHT' and 'BDW'
current template fix for the power status

**Comment by stripes416** [comment]
@xiulipan @Bin-QA can we close this issue now that #84 has been merged?

**Comment by aiChaoSONG** [comment]
close for BYT/CHT/BDW supported
