### ISSUE TITLE
[BUG] sof_remove.sh needs to remove snd_soc_max98390

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof-test#834]
**Describe the bug**
sof_remove.sh fails with sof-adl-max98390, see Intel daily plan #9293

RMMOD	snd_soc_core
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_max98390
snd_soc_max98390       32768  0

**Comment by kv2019i** [comment]
Seen in daily test so P1

**Comment by plbossart** [comment]
snd_soc_max98390 is not a machine driver @kv2019i. It's a codec driver and it has to be handled manually *after* you remove the machine driver.

**Comment by kv2019i** [comment]
@plbossart wrote:
> snd_soc_max98390 is not a machine driver @kv2019i. It's a codec driver and it has to be handled manually _after_ you remove the machine driver.

I stand corrected. It still needs to be removed. And wouldn't it be easier to just remove "snd_soc_*" twice, first bringing down the mach drivers and on second round the codecs. Enumerating these separately adds constant churn to the scripts.

**Comment by plbossart** [comment]
I can't claim I am the expert here, but I would think you will need to iterate more than twice?

We never looked at modprobe -r, not sure if this is any different from rmmod

````  -r, --remove
           This option causes modprobe to remove rather than insert a module. If the modules it depends on are also unused, modprobe will try to remove them too. Unlike insertion, more than one
           module can be specified on the command line (it does not make sense to specify module parameters when removing modules).
````

**Comment by XiaoyunWu6666** [comment]
https://github.com/thesofproject/sof-test/pull/837

**Comment by XiaoyunWu6666** [comment]
Another relevant PR for solving similar problem https://github.com/thesofproject/sof-test/pull/865
