### ISSUE TITLE
[FEATURE] sof_remove.sh: remove all machine drivers

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof-test#835]
**Is your feature request related to a problem? Please describe.**
sof-test update is needed for every new machine driver, causing extra work in terms of filing bugs, updating patches and scripts whenever a new driver is added.

**Describe the solution you'd like**
The script should use lsmod to get list of all snd_soc_* modules and remove them all. This would reduce need to list each and every machine driver with bugs and patches like https://github.com/thesofproject/sof-test/issues/834

Parsing all dependencies might be a bit too complex, so I'd still keep explicit names for the core SOF and ALSA modules (and they should be removed last), but I see little need to iterate all machine drivers. This will also speed up the script if we only go through modules that are actually loaded (not by much as remove_module() already does a check, a bit still).

**Describe alternatives you've considered**

**Additional context**

**Comment by plbossart** [comment]
@kv2019i I think this can be done if you list all the modules, filter out the ones you want to handle manually, and then remove the machine drivers with a loop on an array.

You would still need to keep track of the codec drivers for the insert phase to force the probe, so in the end I am not sure if this saves a lot of time.

To some extent it's really a case that people who add new machine drivers don't seem to use sof-test, and that's a larger problem than maintaining sof-test...
