### ISSUE TITLE
[BUG]  Firmware Bug: TPM interrupt not working, polling instead for new UP Xtreme i11.

### ISSUE THREAD

**Issue by greg-intel** [thesofproject/sof-test#838]
**Describe the bug**
As mentioned [HERE](https://github.com/thesofproject/sof/pull/5207#issuecomment-1012685601) a new device is reporting the following error:
`Jan 13 13:02:49 jf-tglu-up-hda-zephyr-01 kernel: tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead`

**To Reproduce**
TBD

**Expected behavior**
We expect no errors on new device installations.

**Detail Info**
1) Branch name and commit hash of the 3 repositories: sof (firmware/topology), linux (kernel driver) and sof-test (test case)
    * Kernel: ba28f9bb

2) Test report 
    * https://sof-ci.01.org/sofpr/PR5207/build11618/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=verify-kernel-boot-log
3) Test DUT Model (or a brief description about the device)
    * MODEL: TGLU_UP_HDA_ZEPHYR
    * jf-tglu-up-hda-zephyr-01
4) Test TPLG
    * TPLG: irrelevant
5) Test case (what test script and how you run it)
    * TESTCASE: sof-test/test-case/verify-kernel-boot-log.sh

 ### dmidecode differenes
 TPM-Related dmidecode output from jf-tglu-up-hda-zephyr-01:
 ```
 TPM Device
        Vendor ID: IFX
        Specification Version: 2.0      Firmware Revision: 7.85
        Description: INFINEON   Characteristics:
                Family configurable via platform software support
        OEM-specific Information: 0x00000000
 ```
This section doesn't exist for a comparable device, sh-tglu-rvp-hda-zephyr-03

### cpuinfo differences
UP Xtreme Device with the error:
```
ubuntu@jf-tglu-up-hda-zephyr-01:~$ cat /proc/cpuinfo | grep "odel" -C2
vendor_id : GenuineIntel
cpu family : 6
model : 140
model name : 11th Gen Intel(R) Core(TM) i3-1115GRE @ 3.00GHz
stepping : 1
microcode : 0x9a
```
Same board, different CPU without the error:
```
ubuntu@sh-tglu-rvp-hda-zephyr-03:~$ cat /proc/cpuinfo | grep "odel" -C2
vendor_id : GenuineIntel
cpu family : 6
model : 140
model name : Intel(R) Celeron(R) 6305E @ 1.80GHz
stepping : 1
microcode : 0x9a
```

[dmesg.log](https://github.com/thesofproject/sof-test/files/7872817/dmesg.log)

**Comment by marc-hb** [comment]
The BIOS version is the same
```
BIOS Information
        Vendor: American Megatrends International, LLC.
        Version: UXTGBM14
        Release Date: 11/05/2021
```
The most technical discussion I found is this: https://groups.google.com/g/fa.linux.kernel/c/aXDdaseTxOA

@plbossart can we ignore this? After skimming this discussion I'm a bit worried about suspend/resume testing (the usual victim)

**Comment by plbossart** [comment]
we already have one device where we ignore TPM issues

````
ignore_str="$ignore_str"'|tpm tpm0: tpm_try_transmit: send\(\): error -5'
````

if TPM stands indeed for 'Trusted Platform Module" i don't think this should be treated as an SOF error, the audio subsystem does not have any dependencies with that module that I am aware of.

**Comment by marc-hb** [comment]
I understand TPM errors are not audio errors.

USB errors are not audio errors either, however we cannot blindly ignore all USB errors because we need USB for networking and... audio loopback.

In this case I'm especially wondering about suspend/resume which is notoriously unreliable and easily broken by anything.

**Comment by plbossart** [comment]
I don't think there's any dependencies, so let's mask this error and see what the results are. There is no hardware link so not sure what could possibly go wrong (famous last words I know).

**Comment by marc-hb** [comment]
Thanks @plbossart so let's add it to https://github.com/thesofproject/sof-test/blob/bb3569d7524/tools/sof-kernel-log-check.sh

**Comment by marc-hb** [comment]
#840 is merged, re-open if seen again.
