### ISSUE TITLE
[FEATURE] use second SSH to get logs on TIMEOUT

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#839]
**Is your feature request related to a problem? Please describe.**
When suspend/resume fails, it's marked by our CI as TIMEOUT - and no logs are provided.
When this happens in an interactive session, it' usually possible to open another ssh session and get the dmesg log.
Can we try to get the logs via this indirect mechanism?
Otherwise, we'll never know at what point the device was stuck.

**Describe the solution you'd like**
I'd like to get logs even when suspend/resume fails and rtcwake fails.

**Describe alternatives you've considered**
none

**Additional context**
This is needed to progress on experimental branches and remote debug. No logs makes remove debug impossible.

**Comment by marc-hb** [comment]
Multithreading in shell scripts is tricky. I think this would be easier to do at the test runner level instead of in sof-test (~ Jenkins to keep things simple). As you noted, this feature is not needed when using sof-test interactively, it's only needed in automation.

**Comment by plbossart** [comment]
It would be nice to add this feature in sof-test, it's not so good to have a timeout implementation that is handled outside of sof-test.

Multithreading in shell scripts is tricky, but at some point one has to wonder if this was the right decision to use shell scripts... Threads are useful to deal with stuck tests.

**Comment by marc-hb** [comment]
Nothing beats shell scripts to start processes and move files around. Anything more elaborate becomes indeed a problem.

Everything does not have to be in a single language, I mean neither the kernel build system or checkpatch are written in C and Rust is making its way to the kernel. The right tool for the job. In fact we have a test runner in python already on top of sof-test but it's not open-source (and I don't know it).

**Comment by marc-hb** [comment]
> Nothing beats shell scripts to start processes and move files around. Python's subprocess module is a pain to use

Timely example in https://github.com/thesofproject/sof/pull/5299 which is necessary for Windows compatibility.

**Comment by plbossart** [comment]
closing, not super important
