### ISSUE TITLE
[FEATURE] IPC4: verify-firmware-presence.sh: use actual firmware 

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#841]
With the IPC4 file path and filename changes, this test needs to be updated:

````
[   40.931241] sof-audio-pci-intel-tgl 0000:00:1f.3: request_firmware intel/avs/tgl/dsp_basefw.bin successful
````

````+ /root/sof-test/test-case/verify-firmware-presence.sh
2022-01-27 23:55:25 UTC Sub-Test: [INFO] Checking file: /lib/firmware/intel/sof/sof-tgl.ri
````

The paths and filenames need to be updated.

**Comment by marc-hb** [comment]
> Checking file: /lib/firmware/intel/sof/community/sof-tgl.ri

The `/lib/firmware/intel/sof/community/` part comes from `./sof-test/tools/sof-dump-status.py --fwpath`
The `tgl` part comes from `./sof-test/tools/sof-dump-status.py --platform`

`--platform` output comes from a table of PCI and DMI identifiers embedded in `sof-dump-status.py` + some `/sys/` exploration.

`--fwpath` output is mostly hardcoded except for the `community` part that is added based on matching DMI `System Information -> Manufacturer, Product Name` against a list of values embedded in the script.

Is `intel/avs/tgl/dsp_basefw.bin` a good model / good filename example representative of all configurations? For both open and closed source?

This test is designed to PASS before the firmware is loaded. I doubt it's possible to predict the IPC version before the firmware is loaded, is there? So should the test just look for both and pass when any is found?

If this gets too complicated this test should simply be removed from IPC4 test plans. It's never been terribly useful IMHO.

**Comment by marc-hb** [comment]
> Is intel/avs/tgl/dsp_basefw.bin a good model / good filename example representative of all configurations? For both open and closed source?

Thanks @ranj063 for answering this: yes this is a good template for closed source. Open source will hopefully have a template too but a different one, probably something like ` intel/sof/community/sof-abc4.ri`

**Comment by plbossart** [comment]
we are going to use a different path for SOF w/ IPC4, e.g. inte/sof-ipc4/. So I wonder if this test should be removed completely.
It makes no sense anyway because the distribution typically has firmwares installed, but likely not the ones you want to test. This model of hard-coding path and overriding distribution files is not good. We should use /lib/firmware/updates for CI and tests.

**Comment by mengdonglin** [comment]
> we are going to use a different path for SOF w/ IPC4, e.g. inte/sof-ipc4/. So I wonder if this test should be removed completely. It makes no sense anyway because the distribution typically has firmwares installed, but likely not the ones you want to test. This model of hard-coding path and overriding distribution files is not good. We should use /lib/firmware/updates for CI and tests.

@miRoox I think we need to revise our DUT deployment script? What do you think?

**Comment by marc-hb** [comment]
I will upgrade the `installer/Makefile` so it supports the new /lib/firmware layout for IPC4

We should all use the same scripts, laying out files in /lib/firmware/ is not a CI-specific task.

**Comment by mengdonglin** [comment]
@marc-hb Are you good to be the feature owner?

**Comment by marc-hb** [comment]
Yes and the plan is in #855

**Comment by marc-hb** [comment]
Sorry I got confused: the plan in #855 (PR #860) was for bugs #842 and #845, not for this.

**Comment by marc-hb** [comment]
I think we should get rid of this test. At the SOF level we simply have no control on what the `request_firmware()` loader does in the kernel. `request_firmware` does not provide any feedback either and never tells what it loaded and where (which is IMHO a security problem, I digress). I mean it never tells which of multiple paths it picked https://www.kernel.org/doc/html/latest/driver-api/firmware/fw_search_path.html

The good news is `./sof-test/tools/sof-dump-status.py --fwpath` is used only once in sof-test, only in that test. We can change to print `community` or a blank string so it mimics the SOF driver exactly. Callers can then hardcode anything they want if they so desire.

**Comment by plbossart** [comment]
we could also check that the request_firmware succeeds, but if that fails we'll also never see the boot complete stage, so no problem with removing this test.

**Comment by plbossart** [comment]
@marc-hb I can't recall if we ever reached a consensus on this, and if we even have an issue to fix.

**Comment by marc-hb** [comment]
I think people either agree to remove this test from every test plan where it is an issue, or they don't care. No one will miss it.

@thesofproject/test-maintainers
