### ISSUE TITLE
[FEATURE] Skip PAUSE/RELEASE test on Smart Amp playback and capture pipelines

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof-test#866]
**Is your feature request related to a problem? Please describe.**
This feature is to avoid an invalid bug caused by random pause/release on two dependent smart amplifier pipelines, e.g. https://github.com/thesofproject/sof/issues/4434

**Describe the solution you'd like**
multiple-pause-resume.sh can check if a demux/mux or a smart amplifier component is available in a pipeline. If yes, skip doing pause/release on this pipeline.

**Additional context**
When a mux/demux component is there, the involved pipelines have dependency. We cannot do random pause/release on them in parallel.

**Comment by plbossart** [comment]
@mengdonglin it's not feasible to skip a test in sof-test for a specific platform, you have to do this at the CI level.

**Comment by marc-hb** [comment]
> @mengdonglin it's not feasible to skip a test in sof-test for a specific platform,

Why not, can you elaborate? I just did something I think is like it: https://github.com/thesofproject/sof-test/commit/ae421827a419cdef0ea

**Comment by mengdonglin** [comment]
@plbossart @marc-hb I think we have 2 options:

Option 1:  Topology parser will check if there is a demux/mux component in the pipeline. If yes, skip doing pause/release on this pipeline.  And we can still do pause/release other pipelines.  This is preferred solution atm.

Option 2: CI can skip multiple-pause-resume.sh for both TGLU_VOLT_SDW and ADLP_BRYA_SDW.

**Comment by plbossart** [comment]
@marc-hb I don't understand your point and why we would add such work-around in sof-test. 

My point is that we don't want to encode which devices are used for smart-amp capture in the test. You can disable capture if you want, but you disable ALL capture devices then. Going to the lower level details makes no sense and is dependent on topology.

**Comment by marc-hb** [comment]
> I don't understand your point

I don't know what point I'm trying to make, I'm merely asking why something can't or shouldn't be done.

> and why we would add such work-around in sof-test.

If some configuration is not supported then it should not be tested; this is not a "workaround". Now there is of course the recurring problem that sof-test has neither a test runner nor a default test plan, at least none open-source and integrated but that's a different question.

> My point is that we don't want to encode which devices are used for smart-amp capture in the test.

Agreed.

> Going to the lower level details makes no sense and is dependent on topology.

We already have plenty of code in sof-test to analyze topologies:
- https://github.com/thesofproject/sof/tree/main/tools
- #471

**Comment by keqiaozhang** [comment]
I submitted a simple PR https://github.com/thesofproject/sof-test/pull/871 to skip the PAUSE/RELEASE test on Smart Amp playback and Echo Reference capture pipelines.
This PR will only filter out these 2 pipelines and the rest of pipelines will still be tested.

**Comment by mengdonglin** [comment]
Close this issue as PR #871 got merged.
