### ISSUE TITLE
[BUG] Filter out IGB/e1000e errors

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#887]
Found in Intel test "11662?model=WHL_UPEXT_HDA_IPC4&testcase=check-suspend-resume-50"

````
[ 4319.743482] kernel: e1000e 0000:00:1f.6 eno1: Failed to disable ULP
[ 4321.663761] kernel: e1000e 0000:00:1f.6 eno1: Hardware Error
````

**Comment by marc-hb** [comment]
Fixed by either disabling Ethernet in the BIOS or by blocklisting `e10001:
- https://github.com/thesofproject/kconfig/pull/73
