### ISSUE TITLE
check-kmod-load-unload-after-playback.sh log naming is confusing.

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#89]
check-kmod-load-unload-after-playback.sh have pattern like

```
playback 0 // the log named as aplay_hw:0,0_1.tx
kmod reload
playback 1 // the log named looks same as aplay_hw:0,0_1.txt
```

**Comment by Bin-QA** [comment]
this file create by check-playback.sh

**Comment by stripes416** [comment]
@Bin-QA I like the solution youve presented in your branch.

**Comment by Bin-QA** [comment]
@stripes416 thank you, I forget to create the PR

**Comment by stripes416** [comment]
Closing with merge of #94
