### ISSUE TITLE
[BUG] filter out ptp_kvm issues

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#891]
Across the board fails in https://sof-ci.sh.intel.com/#/result/planresultdetail/11848 (public test results not available after two hours of tests).

````
[    1.559736] kernel: fail to initialize ptp_kvm
````

I have no idea what on earth this could be.

**Comment by marc-hb** [comment]
This was fixed a long time ago by kconfig change
- https://github.com/thesofproject/kconfig/pull/70
