### ISSUE TITLE
[FEATURE] dump PM stats on suspend-resume rtcwake error

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#898]
**Is your feature request related to a problem? Please describe.**

we routinely have suspend/resume failures with rtcwake reporting a write error

I believe this case happens when we see the error in dmesg

"Some devices failed to suspend, or early wake event detected"

I will make the conjecture that 90% of the current 'errors' are related to this message. Since it's cryptic, we would need additional information to figure out if issues are audio-related or not, and in the latter case investigate if they are severe or not.

**Describe the solution you'd like**

dump all the information provided in /sys/power/susped_stats, and check if the numbers reported in failed_suspend/failed_resume increase during cycles

````
root@pbossart-mobl3:/sys/power/suspend_stats# ls
fail            failed_resume        failed_suspend        last_failed_dev    success
failed_freeze   failed_resume_early  failed_suspend_late   last_failed_errno
failed_prepare  failed_resume_noirq  failed_suspend_noirq  last_failed_step
````

What is specifically interesting is the 'last_failed_dev' string which should tell us if the problem is audio -related or not.

**Describe alternatives you've considered**

modify the kernel so that __pm_pr_dbg provides the results in all cases, not just when the log level is DEBUG.

**Comment by plbossart** [comment]
@marc-hb @keqiaozhang @ranj063 @XiaoyunWu6666 @fredoh9 comments?

**Comment by marc-hb** [comment]
@plbossart are recent sof-test changes enough, close as done?
