### ISSUE TITLE
[BUG] Fallback to extract pipelines from proc causes green failure in SOF test 

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#913]
**Describe the bug**
On the PR test on CML_RVP_SDW_ZEPHYR, the SOF card disappeared in the middle due to unknown issue. If SOF card is not detected from the system, sof-test will try to extract pipelines from /proc, which usually are pipelines from USB sound card/Nvidia graphic card.
This causes green failures in SOF test.

For example, the passed case check-playback-10sec.sh actually tests USB sound card.

![image](https://user-images.githubusercontent.com/52959957/170614374-750f393d-eac9-43dd-984a-e63ec6a84a33.png)

https://sof-ci.01.org/linuxpr/PR3642/build146/devicetest/
https://sof-ci.01.org/linuxpr/PR3645/build155/devicetest

**Expected behavior**
Fallback behavior should be under control, we should have an option to enable/disable Fallback mode, because we also use sof-test to  test legacy HDA.

**Comment by marc-hb** [comment]
@aiChaoSONG did you fix this? I remember some PR of yours...

**Comment by aiChaoSONG** [comment]
Oh, Yeah, let's close this issue.

**Comment by aiChaoSONG** [comment]
fixed by: https://github.com/thesofproject/sof-test/pull/914
