### ISSUE TITLE
[new feature]tplgtool to output dot file and dot graph

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#95]
To generate visible  graph for tplg, we can convert the graph in tplg into dot format. And use dot to create a png graph.

Example sof-apl-pcm512x.tplg.dot file and sof-apl-pcm512x.tplg.png file is attached.
![sof-apl-pcm512x tplg](https://user-images.githubusercontent.com/37825714/75525366-b214aa80-5a4a-11ea-8596-c21d58b39e03.png)
[sof-apl-pcm512x.tplg.dot.txt](https://github.com/thesofproject/sof-test/files/4266094/sof-apl-pcm512x.tplg.dot.txt)

CMD used to generate doc file to png is `dot %s.dot -Tpng -o %s.png`

**Comment by xiulipan** [comment]
@lgirdwood new issue for a scripts version tool is here.
@aiChaoSONG Here is some example for graph, if we can find some Python lib to direct generate graph like this is also OK. Please help to have some first version with simple dot.

**Comment by aiChaoSONG** [comment]
@xiulipan @lgirdwood This is a good idea. I will start working on this next week

**Comment by lgirdwood** [comment]
@aiChaoSONG @xiulipan looks good :-)

**Comment by aiChaoSONG** [comment]
@lgirdwood @xiulipan PR is here https://github.com/thesofproject/sof-test/pull/96, please give it some try.

**Comment by aiChaoSONG** [comment]
this is done, close
