### ISSUE TITLE
ADLP_GMB_I2S kmod test failed, AMP is not ready to run calibration

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#960]
This is found internal test 15420 with UPSTREAM merge PR https://github.com/thesofproject/linux/pull/3859
15420?model=ADLP_GMB_I2S&testcase=check-kmod-load-unload-after-playback-5

For ADLP_GMB_I2S, kmod test failded with this error.

```
[ 6722.552819] kernel: max98390 i2c-MX98390:00: AMP is not ready to run calibration
[ 6722.554197] kernel: max98390 i2c-MX98390:01: AMP is not ready to run calibration
```

**Comment by fredoh9** [comment]
Initially we may ignore this error. In 2nd thought, probably we need to move this to linux repo.
Suspend resume test also has different i2c-MX98390 errors.

```
[  357.577318] kernel: max98390 i2c-MX98390:00: ret=-108, Failed to read: 0x24FF
[  357.577779] kernel: max98390 i2c-MX98390:01: ret=-108, Failed to read: 0x24FF
[  357.957059] kernel: rt5682s i2c-RTL5682:00: Device with ID register c103d020 is not rt5682s
```

**Comment by marc-hb** [comment]
Has this been seen recently?
cc: @keqiaozhang
