### ISSUE TITLE
[BUG] EHL_RVP_I2S has intel_ish_ipc errors in suspend-resume test

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#983]
- Kernel Branch: topic/sof-dev
- Kernel Commit: [592a3f2a6456]
- SOF Branch: stable-v2.2
- SOF Commit: [afe466da0238]
- Zephyr Commit: [fa2054f93e4e]

cmd: TPLG=/lib/firmware/intel/sof-tplg/sof-ehl-rt5660.tplg MODEL=EHL_RVP_I2S ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 25 -m capture
Internal test result link: 17606?model=EHL_RVP_I2S&testcase=check-suspend-resume-with-capture-25

```
===========================>>
[14663.198353] kernel: intel_ish_ipc 0000:00:1d.0: enable ose_gpe failed
<<===========================
```

**Comment by marc-hb** [comment]
wontfix
